I added a few pages translated into Turkish.
withastro/starlight pull request #1038
Opened 2023-11-03 14:35 UTC by hamer1818

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- I added a few pages translated into Turkish.

2023-11-03 14:36 UTC, astrobot-houston reviewed
Hello! Thank you for opening your **first PR** to Starlight! ✨

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any issues you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🤩

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2023-11-03 15:51 UTC, HiDeoo reviewed
Thanks for the translations :raised_hands:

I have not reviewed any of the translations yet but I am suggesting a few changes to make the build pass in case this can help.

To explain what is happening, some relative import paths need to be updated as the Turkish translations are in a nested `tr` folder compared to the English ones.

2023-11-03 15:51 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/css-and-tailwind.mdx
> +import ThemeDesigner from '../../../components/theme-designer.astro';
```suggestion
import ThemeDesigner from '../../../../components/theme-designer.astro';
```

2023-11-03 15:51 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/customization.mdx
> +import FileTree from '../../../components/file-tree.astro';
```suggestion
import FileTree from '../../../../components/file-tree.astro';
```

2023-11-03 15:51 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/i18n.mdx
> +import FileTree from '../../../components/file-tree.astro';
```suggestion
import FileTree from '../../../../components/file-tree.astro';
```

2023-11-03 15:51 UTC, HiDeoo commented on docs/src/content/docs/tr/reference/configuration.mdx
> +import SocialLinksType from '../../../components/social-links-type.astro';
```suggestion
import SocialLinksType from '../../../../components/social-links-type.astro';
```

2023-11-03 17:17 UTC, hamer1818 commented
> Thanks for the translations :raised_hands:
> 
> I have not reviewed any of the translations yet but I am suggesting a few changes to make the build pass in case this can help.
> 
> To explain what is happening, some relative import paths need to be updated as the Turkish translations are in a nested `tr` folder compared to the English ones.

I never thought of this, thank you.

2023-11-07 09:27 UTC, delucis requested changes
Thank you for this big PR @hamer1818! I appreciate you taking the time to help make our docs available to readers of Turkish.

Took me a while to go through, but left quite a few comments. 90% of these are making sure that links point to the `/tr/` version of pages and use the correct `#` links for headings translated to Turkish. I also noticed a few formatting fixes and left a couple of questions.

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/overrides.md
> +Her sayfanın üstünde görüntülenen [`banner`](/reference/frontmatter#banner) bileşeni.
```suggestion
Her sayfanın üstünde görüntülenen [`banner`](/tr/reference/frontmatter#banner) bileşeni. 
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/overrides.md
> +Frontmatter’da [`hero`](/reference/frontmatter#hero) ayarlandığında sayfanın üstünde görüntülenen bir bileşen.
```suggestion
Frontmatter’da [`hero`](/tr/reference/frontmatter#hero) ayarlandığında sayfanın üstünde görüntülenen bir bileşen. 
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/guides/i18n.mdx
> +   }
This should be left in English as indicated by the line immediately above this code block:

> İşte Starlight'ın varsayılan İngilizce değerleri:


```suggestion
   {
   	"skipLink.label": "Skip to content",
   	"search.label": "Search",
   	"search.shortcutLabel": "(Press / to Search)",
   	"search.cancelLabel": "Cancel",
   	"search.devWarning": "Search is only available in production builds. \nTry building and previewing the site to test it out locally.",
   	"themeSelect.accessibleLabel": "Select theme",
   	"themeSelect.dark": "Dark",
   	"themeSelect.light": "Light",
   	"themeSelect.auto": "Auto",
   	"languageSelect.accessibleLabel": "Select language",
   	"menuButton.accessibleLabel": "Menu",
   	"sidebarNav.accessibleLabel": "Main",
   	"tableOfContents.onThisPage": "On this page",
   	"tableOfContents.overview": "Overview",
   	"i18n.untranslatedContent": "This content is not available in your language yet.",
   	"page.editLink": "Edit page",
   	"page.lastUpdated": "Last updated:",
   	"page.previousLink": "Next",
   	"page.nextLink": "Previous",
   	"404.text": "Page not found. Check the URL or try using the search bar."
   }
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/guides/i18n.mdx
> +   ```
Same here:

````suggestion
   ```json
   {
   	"pagefind.clear_search": "Clear",
   	"pagefind.load_more": "Load more results",
   	"pagefind.search_label": "Search this site",
   	"pagefind.filters_label": "Filters",
   	"pagefind.zero_results": "No results for [SEARCH_TERM]",
   	"pagefind.many_results": "[COUNT] results for [SEARCH_TERM]",
   	"pagefind.one_result": "[COUNT] result for [SEARCH_TERM]",
   	"pagefind.alt_search": "No results for [SEARCH_TERM]. Showing results for [DIFFERENT_TERM] instead",
   	"pagefind.search_suggestion": "No results for [SEARCH_TERM]. Try one of the following searches:",
   	"pagefind.searching": "Searching for [SEARCH_TERM]..."
   }
   ```
````

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/guides/overriding-components.md
> +  <a href="mailto:houston@example.com">Bana E-posta Gönder</a>
Looks like the indentation here is causing issues:

<img width="795" alt="image" src="https://github.com/withastro/starlight/assets/357379/330fcc81-37c3-4d80-8f22-db7fcc920d2b">


This should fix it:

```suggestion
   ---
   // src/components/EmailLink.astro
   import type { Props } from '@astrojs/starlight/props';
   ---

   <a href="mailto:houston@example.com">Bana E-posta Gönder</a>
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/guides/overriding-components.md
> +  });
Same is likely the case here although we can’t see it yet:
```suggestion
   // astro.config.mjs
   import { defineConfig } from 'astro/config';
   import starlight from '@astrojs/starlight';

   export default defineConfig({
     integrations: [
       starlight({
         title: 'Geçersiz Kılmalarla Benim Belgelerim',
         components: {
           // Varsayılan `SocialIcons` bileşenini geçersiz kıl.
           SocialIcons: './src/components/EmailLink.astro',
         },
       }),
     ],
   });
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/configuration.mdx
> +### `titleDelimiter | başlıkAyırıcı`
In general we don’t translate these headings which are code options, so I guess this should match that?

```suggestion
### `titleDelimiter`
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/frontmatter.md
> +### `title` (Gerekli)
Noticed that “gerekli” is lowercase in the configuration reference. Should it be the same here?

```suggestion
### `title` (gerekli)
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/frontmatter.md
> +[global `editLink` yapılandırmasını](/reference/configuration/#editlink) geçersiz kılar. Belirli bir sayfa için "Sayfayı Düzenle" bağlantısını devre dışı bırakmak için `false` olarak ayarlayın veya b
Should the start of the sentence here be capitalised?

```suggestion
[Global `editLink` yapılandırmasını](/tr/reference/configuration/#editlink) geçersiz kılar. Belirli bir sayfa için "Sayfayı Düzenle" bağlantısını devre dışı bırakmak için `false` olarak ayarlayın veya bu sayfanın içeriğinin düzenlenebileceği alternatif bir URL sağlayın.
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/frontmatter.md
> +**Tür:** [`HeadConfig[]`](/reference/configuration/#headconfig)
```suggestion
**Tür:** [`HeadConfig[]`](/tr/reference/configuration/#headconfig)
```

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/frontmatter.md
> +**varsayılan:** `'doc'`
Noticing here that “Tür” capitalised but “varsayılan” is not. Should they be consistent?

There are a few places on this page like this.

2023-11-07 09:27 UTC, delucis commented on docs/src/content/docs/tr/reference/overrides.md
> +Starlight'ın yerleşik bileşenlerini, Starlight'ın [`components`](/reference/configuration#components) yapılandırma seçeneğinde yer değiştirme bileşenlerinin yolunu sağlayarak geçersiz kılabilirsiniz.
```suggestion
Starlight'ın yerleşik bileşenlerini, Starlight'ın [`components`](/tr/reference/configuration#components) yapılandırma seçeneğinde yer değiştirme bileşenlerinin yolunu sağlayarak geçersiz kılabilirsiniz.
```

2023-11-07 22:47 UTC, hamer1818 commented
i updated a new one

2023-11-07 22:47 UTC, closed without merging