i18n(es): Update `getting-started.mdx`
withastro/starlight pull request #1042
Opened 2023-11-04 19:56 UTC by Waxer59

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- What does this PR change? Give us a brief description.
Update `getting-started.mdx` [`0100298`](https://github.com/withastro/starlight/commit/0100298b158f90cf2beed67e9a185f40a533465b)

2023-11-04 19:59 UTC, Waxer59 commented on docs/src/content/docs/es/getting-started.mdx
> +Starlight está listo para que añadas nuevo contenido o traigas ¡tus archivos existentes!.
```suggestion
Starlight está listo para que añadas nuevo contenido o ¡traigas tus archivos existentes!.
```

2023-11-04 20:08 UTC, Waxer59 commented on docs/src/content/docs/es/getting-started.mdx
> +import FileTree from '../../components/file-tree.astro';
```suggestion
import FileTree from '../../../components/file-tree.astro';
```

2023-11-04 20:22 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-06 21:23 UTC, delucis requested changes
Thank you for the update @Waxer59 — and thanks for reviewing @dreyfus92!

Just caught a few links we need to fix.

2023-11-06 21:23 UTC, delucis commented on docs/src/content/docs/es/getting-started.mdx
> +Cuando trabajas localmente, el [servidor de desarrollo de Astro](https://docs.astro.build/en/reference/cli-reference/#astro-dev) te permite previsualizar tu trabajo y actualiza automáticamente tu nav
We should link to the Spanish docs here:

```suggestion
Cuando trabajas localmente, el [servidor de desarrollo de Astro](https://docs.astro.build/es/reference/cli-reference/#astro-dev) te permite previsualizar tu trabajo y actualiza automáticamente tu navegador cuando realizas cambios.
```

2023-11-06 21:23 UTC, delucis commented on docs/src/content/docs/es/getting-started.mdx
> +- **Despliega:** Publica tu trabajo siguiendo la guía [“Despliega tu sitio”](https://docs.astro.build/en/guides/deploy/) en la documentación de Astro.
Same here:
```suggestion
- **Despliega:** Publica tu trabajo siguiendo la guía [“Despliega tu sitio”](https://docs.astro.build/es/guides/deploy/) en la documentación de Astro.
```

2023-11-06 21:23 UTC, delucis commented on docs/src/content/docs/es/getting-started.mdx
> +- **Componentes:** Descubre tarjetas incorporadas, pestañas y más en la guía [“Componentes”](/guides/components/).
Looks like these links need fixing:

```suggestion
- **Configura:** Aprende acerca de las opciones comunes en [“Personalizando Starlight”](/es/guides/customization/).
- **Navega:** Configura tu barra lateral siguiendo la guía [“Barra Lateral de Navegación”](/es/guides/sidebar/).
- **Componentes:** Descubre tarjetas incorporadas, pestañas y más en la guía [“Componentes”](/es/guides/components/).
```

2023-11-06 21:23 UTC, delucis commented on docs/src/content/docs/es/getting-started.mdx
> +Utiliza las páginas de referencia de [configuración del proyecto](/reference/configuration/) y [configuración del frontmatter de páginas individuales](/reference/frontmatter/) para asegurarte de que
Same here:

```suggestion
Utiliza las páginas de referencia de [configuración del proyecto](/es/reference/configuration/) y [configuración del frontmatter de páginas individuales](/es/reference/frontmatter/) para asegurarte de que tu sitio de Starlight esté configurado y funcione correctamente. 
```

2023-11-06 21:23 UTC, delucis commented on docs/src/content/docs/es/getting-started.mdx
> +Si no encuentras la respuesta en la documentación, visita la [documentación completa de Astro](https://docs.astro.build) para obtener la documentación completa de Astro.
And it probably also makes sense here to link to the Spanish version of the Astro Docs:

```suggestion
Si no encuentras la respuesta en la documentación, visita la [documentación completa de Astro](https://docs.astro.build/es/) para obtener la documentación completa de Astro.
```

2023-11-06 21:23 UTC, delucis commented on docs/src/content/docs/es/getting-started.mdx
> +Consulta las [instrucciones de configuración manual](/manual-setup/) para agregar Starlight a un proyecto de Astro existente.
Last one!

```suggestion
Consulta las [instrucciones de configuración manual](/es/manual-setup/) para agregar Starlight a un proyecto de Astro existente.
```

2023-11-06 23:40 UTC, Waxer59 commented
Thanks for the review 🤠!,

2023-11-07 06:36 UTC, kevinzunigacuellar approved these changes
Let's Get This Moving 😆

2023-11-07 10:19 UTC, delucis approved these changes
Nice work team 🙌

2023-11-07 10:20 UTC, merged