i18n(es): Translate `plugins`
withastro/starlight pull request #1177
Opened 2023-12-01 06:13 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Translated `plugins` to spanish

2023-12-01 17:41 UTC, Villanuevand requested changes
There are some paragraphs you missed to translate. 
Everything else LGTM!

2023-12-01 17:41 UTC, Villanuevand commented on docs/src/content/docs/es/reference/plugins.md
> +This configuration may have been updated by other plugins configured before the current one.
This part should be translated too.

2023-12-01 21:38 UTC, dreyfus92 commented
Muchas gracias por la revisión @Villanuevand

2023-12-02 04:06 UTC, kevinzunigacuellar reviewed
Thanks @dreyfus92, I left a couple comments for clarity.

2023-12-02 04:06 UTC, kevinzunigacuellar commented on docs/src/content/docs/es/reference/plugins.md
> +En el siguiente ejemplo, una nueva cuenta de redes sociales se añade a la configuración existente de [`social`](/reference/configuration/#social) extendiendo `config.social` en el nuevo objeto `socia
```suggestion
En el siguiente ejemplo, se agrega una nueva cuenta en [`social`](/reference/configuration/#social) a la configuración existente extendiendo 'config.social' en el nuevo objeto social:
```

2023-12-02 04:39 UTC, merged