i18n(pt-br): add `reference/plugins.md`
withastro/starlight pull request #1199
Opened 2023-12-01 21:43 UTC by daniloraisi

#### What does this PR change?

- Changes or translations of Starlight docs site contents.

#### Description

This PR adds the Portuguese version of the `reference/plugins.md` page.

2023-12-02 05:22 UTC, vasfvitor requested changes

2023-12-02 05:22 UTC, vasfvitor commented on docs/src/content/docs/pt-br/reference/plugins.md
> +Os plugins do Starlight podem personalizar a configuração, UI, e comportamento, enquanto traz facilidade em compartilhar e reutilizar.
>enquanto traz facilidade em compartilhar e reutilizar.

I feel this could be improved. It sounds odd to me.

2023-12-02 05:22 UTC, vasfvitor commented on docs/src/content/docs/pt-br/reference/plugins.md
> +Essa página documenta as referências da API que os plugins tem acesso.
```suggestion
Essa página de referência documenta a API que os plugins tem acesso.
```

2023-12-02 05:22 UTC, vasfvitor commented on docs/src/content/docs/pt-br/reference/plugins.md
> +`false` quando o servidor dev é iniciado, `true` quando uma atualização é disparada.
```suggestion
`false` quando o servidor de desenvolvimento é iniciado, `true` quando uma atualização é disparada.
```
To match with `getting-started.mdx` 
https://github.com/withastro/starlight/blob/9625926fe603d35d7cf096eba32c74bd469661b3/docs/src/content/docs/pt-br/getting-started.mdx#L49

2023-12-02 05:40 UTC, vasfvitor commented
Btw, I forgot to welcome you. Welcome! :D. Thank you very much for putting this in. Make sure you are on [Astro discord ](https://astro.build/chat) to receive a warm welcome when this or the other PR gets in.

2023-12-03 16:32 UTC, vasfvitor commented on docs/src/content/docs/pt-br/reference/plugins.md
> +Um cópia somente-leitura da [Configuração do Starlight](/pt-br/reference/configuration/) fornecida pelo usuário.
I agree

2023-12-03 16:33 UTC, vasfvitor commented on docs/src/content/docs/pt-br/reference/plugins.md
> +Os plugins do Starlight podem personalizar a configuração, UI, e comportamento, enquanto traz facilidade em compartilhar e reutilizar.
perfect!

2023-12-05 13:34 UTC, daniloraisi commented on docs/src/content/docs/pt-br/reference/plugins.md
> +O exemplo acima, registrará uma mensagem de log que inclui a informação fornecida:
I've changed the text to “O exemplo acima registrará um log que inclui a mensagem `info` fornecida:” to avoid the repetition of the word “mensagem”.

2023-12-05 13:42 UTC, daniloraisi commented
Thanks for the welcome @vasfvitor and @Fryuni!

I'm starting using Astro on some projects, and I came to Starlight from their documentation.

There is nothing better to dive into a project than digging into the documentation and working with some translations.

2023-12-05 17:41 UTC, vasfvitor approved these changes
other than that LGTM! Anything else @Fryuni?

2023-12-05 17:41 UTC, vasfvitor commented on docs/src/content/docs/pt-br/reference/plugins.md
> +Função de setup chamada quanto o Starlight é iniciado (durante a execução do hook de integração [`astro:config:setup`](https://docs.astro.build/pt-br/reference/integrations-reference/#astroconfigsetu
```suggestion
Função de setup chamada quando o Starlight é iniciado (durante a execução do hook de integração [`astro:config:setup`](https://docs.astro.build/pt-br/reference/integrations-reference/#astroconfigsetup)).
```

2023-12-05 21:07 UTC, Fryuni approved these changes
LGTM

2023-12-05 21:08 UTC, Fryuni commented
GitBug attacks again 😆

2023-12-15 23:35 UTC, delucis approved these changes
Thank you for your translation @daniloraisi! We really appreciate you getting involved.

And thank you for the careful review and warm welcome @vasfvitor and @Fryuni — love to see it 😍

2023-12-15 23:37 UTC, merged