i18n(es): update `docs/guide/authoring-content.md`
withastro/starlight pull request #1200
Opened 2023-12-02 02:33 UTC by narcecl

#### What does this PR change?
- Changes or translations of Starlight docs site contents.

#### Description
This PR adds the Spanish translation of `docs/guides/authoring-content` page.

2023-12-02 02:34 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Starlight! ✨

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any issues you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🤩

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2023-12-07 03:39 UTC, dreyfus92 requested changes
Buen trabajo @narcecl 😁, te dejo alguna sugerencias. También te sugiero si tienes oportunidad, de revisar el documento en inglés para la traducción sea lo más consistente hablando de espacios, negritas, etc.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +```js {2-3}
Este espacio si es necesario, por que así está en la versión de inglés.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +````
Igual aquí.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +  // Individual terms can be highlighted, too
Igual aquí. Los comentarios pueden ser traducidos y estaba bien el original.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +    return 'Even regular expressions are supported';
Los mismo aquí.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +  // Individual terms can be highlighted, too
También lo de los comentarios y el espacio.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +    return 'Even regular expressions are supported';
Puede ser traducido el string, el original es válido.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +````
El espacio aquí es necesario.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +```js "return true;" ins="insertados" del="eliminados"
Aquí igual.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +Un marco que se parece a una ventana de una terminal se utilizará para todos los demás lenguajes de programación (por ejemplo, `bash`o `sh`).
El original me parece correcto.

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +### Apartado tipo nota
```suggestion
### Nota aparte
```

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +Hay tres estilos de resaltado: **neutral** para llamar la atención sobre el código, **verde** para indicar código insertado y **rojo** para indicar código eliminado.
```suggestion
Hay tres estilos de resaltado: neutral para llamar la atención sobre el código, verde para indicar código insertado y rojo para indicar código eliminado.
```

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +````
Faltan todos los espacios agregarlos de nuevo

2023-12-07 03:39 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/authoring-content.md
> +Los apartados (también conocidos como “alertas” o ”llamados de atención”) son útiles para mostrar información secundaria junto al contenido principal de una página.
```suggestion
Los apartados (también conocidos como “advertencias” o ”leyendas”) son útiles para mostrar información secundaria junto al contenido principal de una página.
```

2023-12-07 15:26 UTC, Waxer59 reviewed
¡Gracias por la PR 🤠!, te dejo unas sugerencias

2023-12-07 15:26 UTC, Waxer59 commented on docs/src/content/docs/es/guides/authoring-content.md
> +## Frontmatter
En mi opinión, no sería necesario volver a traducir esta sección, dado que la traducción actual es correcta.

2023-12-07 15:26 UTC, Waxer59 commented on docs/src/content/docs/es/guides/authoring-content.md
> +Los apartados de `caution` y `danger` son útiles para llamar la atención del usuario sobre detalles que podrían generar problemas.
En este párrafo no usamos los backticks (`) para resaltar en el texto ya que en el documento original no se encuentra resaltado.
```suggestion
Los apartados de caution y danger son útiles para llamar la atención del usuario sobre detalles que podrían generar problemas. Si te encuentras utilizando estos tipos de apartados con frecuencia, también puede ser una señal de que lo que estás documentando podría beneficiarse de una reestructuración o rediseño.
```

2023-12-07 15:26 UTC, Waxer59 commented on docs/src/content/docs/es/guides/authoring-content.md
> +Si te encuentras utilizando estos tipos de apartados con frecuencia, también puede ser una señal de que lo que estás documentando podría beneficiarse de una reestructuración o rediseño.
```suggestion
```

2023-12-07 15:29 UTC, Waxer59 commented on docs/src/content/docs/es/guides/authoring-content.md
> +Un marco que se parece a una ventana de una terminal se utilizará para todos los demás lenguajes de programación (por ejemplo, `bash`o `sh`).
En mi opinión el texto original es correcto

2023-12-10 21:27 UTC, closed without merging

2023-12-15 23:23 UTC, delucis commented
Hey @narcecl! Just double checking you intended to close this pull request?