i18n(es): Update `plugins.md`, `configuration.mdx` & `showcase.mdx`
withastro/starlight pull request #1297
Opened 2023-12-18 23:25 UTC by Waxer59

#### Description

- What does this PR change? Give us a brief description.
Update `plugins.md`, `configuration.mdx` & `showcase.mdx` [`87659f0`](https://github.com/withastro/starlight/commit/87659f061ea6d73be4bd48063a2e3f025adb0514)

2023-12-19 14:42 UTC, dreyfus92 commented on docs/src/content/docs/es/showcase.mdx
> +		description="Reemplaza Pagefind, el proveedor de búsqueda predeterminado, con Algolia DocSearch."
Te dejo una pequeña sugerencias @Waxer59, buen trabajo 😁
```suggestion
		description="Reemplaza Pagefind, el proveedor de búsqueda predeterminado con Algolia DocSearch."
```

2023-12-19 15:03 UTC, Waxer59 commented
Listo!, muchas gracias por la revisión 🤠

2023-12-19 15:19 UTC, dreyfus92 approved these changes
LGTM ✅

2023-12-19 22:16 UTC, delucis requested changes
Thanks for the PR @Waxer59! I noticed one small link issue.

Could you also update this PR with the changes from #1301? We moved one more plugin.

2023-12-19 22:16 UTC, delucis commented on docs/src/content/docs/es/showcase.mdx
> +		href="/guides/site-search/#algolia-docsearch"
One detail here, this link should be to the Spanish page:

```suggestion
		href="/es/guides/site-search/#algolia-docsearch"
```

Easy to miss with the format so different from links.

2023-12-20 08:44 UTC, Waxer59 commented
review and new changes applied, thanks for the review 🤠!

2023-12-20 17:55 UTC, kevinzunigacuellar reviewed
Gracias por la PR @Waxer59 y la revisión @dreyfus92 . Dejé unos pequeños comentarios

2023-12-20 17:55 UTC, kevinzunigacuellar commented on docs/src/content/docs/es/showcase.mdx
> +Estas herramientas de la comunidad e integraciones pueden utilizarse para añadir características a tu sitio de Starlight.
```suggestion
Estas herramientas de la comunidad e integraciones pueden utilizarse para añadir funcionalidades a tu sitio de Starlight.
```

2023-12-20 17:55 UTC, kevinzunigacuellar commented on docs/src/content/docs/es/reference/plugins.md
> +Aprende más sobre el uso de un plugin de Starlight en la [Referencia de Configuración](/es/reference/configuration/#plugins) o visita el [mostrador de plugins](/es/showcase/#plugins) para ver una lis
```suggestion
Aprende más sobre el uso de un plugin de Starlight en la [Referencia de Configuración](/es/reference/configuration/#plugins) o visita la [exhibición de plugins](/es/showcase/#plugins) para ver una lista de los plugins disponibles.
```

2023-12-20 17:55 UTC, kevinzunigacuellar commented on docs/src/content/docs/es/showcase.mdx
> +¿Has construido un sitio de Starlight, plugin o una herramienta para Starlight?
```suggestion
¿Has construido un sitio de Starlight, un plugin o una herramienta para Starlight?
```

2023-12-20 18:02 UTC, Waxer59 commented
Cambios aplicados, muchas gracias por la revisión @kevinzunigacuellar 🤠!

2023-12-22 22:10 UTC, kevinzunigacuellar approved these changes

2023-12-30 06:52 UTC, dreyfus92 commented
Is there something still missing on this PR? cc @delucis @kevinzunigacuellar

2024-01-02 23:16 UTC, delucis approved these changes
Looks great! Thanks for your patience over the holidays 🤗

2024-01-02 23:17 UTC, merged