i18n(it): Modified frontmatter.md and overrides.md
withastro/starlight pull request #1457
Opened 2024-02-04 03:58 UTC by casungo

#### Description

Updated and translated `frontmatter.md` and `overrides.md` so now all of the files in the reference folder are more true to the english version.

2024-02-08 16:33 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view).

I left a few suggestions, mostly aesthetic, but except for that, this looks great to me and we should be able to merge this soon :thumbsup:

2024-02-08 16:33 UTC, HiDeoo commented on docs/src/content/docs/it/reference/frontmatter.md
> +**tipo:** `boolean`
```suggestion
**tipo:** `boolean`  
```

Small tweak to get the type and default value on different lines.

2024-02-08 16:33 UTC, HiDeoo commented on docs/src/content/docs/it/reference/frontmatter.md
>    hidden: vero
```suggestion
  hidden: true
```

Not related to your changes but should not be translated.

2024-02-08 16:33 UTC, HiDeoo commented on docs/src/content/docs/it/reference/frontmatter.md
> +**tipo:** Schema Zod o funzione che restituisce uno schema Zod
```suggestion
**tipo:** Schema Zod o funzione che restituisce uno schema Zod  
```

Same as above to spread the type and default value on 2 lines.

2024-02-08 22:53 UTC, casungo commented
Thank you for your review! I pushed a commit now, should be everything :)

2024-02-09 08:40 UTC, HiDeoo approved these changes
Thanks for the quick update, this looks perfect to me :raised_hands:

2024-02-09 08:44 UTC, merged