i18n(es): Updated `components.mdx` & `i18n.mdx`
withastro/starlight pull request #148
Opened 2023-06-05 12:14 UTC by Waxer59

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- What does this PR change? Give us a brief description.
Updated `components.mdx` & `i18n.mdx`
* [c2b2a17](https://github.com/withastro/starlight/commit/c2b2a1793246e976b82dcee9f2efa695352b48b9)

2023-06-05 14:59 UTC, dreyfus92 requested changes
Te dejo una sugerencia @Waxer59, buen trabajo 😁

2023-06-05 14:59 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/components.mdx
> +Un `<Card>` requiere un `title` y opcionalmente puede incluir un atributo `icon` establecido con el nombre de [uno de los iconos integrados de Starlight](https://github.com/withastro/starlight/blob/m
```suggestion
El componente `<Card>` requiere un `title` y opcionalmente puede incluir un atributo `icon` establecido con el nombre de [uno de los iconos integrados de Starlight](https://github.com/withastro/starlight/blob/main/packages/starlight/components/Icons.ts).
```

2023-06-05 20:19 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-06-06 20:39 UTC, Waxer59 commented on docs/src/content/docs/es/guides/i18n.mdx
> +Starlight proporciona de forma predeterminada traducciones para los textos utilizados en la UI al inglés, alemán, japonés, portugués y español. También damos la bienvenida a [contribuciones para agre
I have already added the French, what names do you mean?

2023-06-06 20:43 UTC, delucis commented on docs/src/content/docs/es/guides/i18n.mdx
> +Starlight proporciona de forma predeterminada traducciones para los textos utilizados en la UI al inglés, alemán, japonés, portugués y español. También damos la bienvenida a [contribuciones para agre
I think @Yan-Thomas meant that in English we write with capital letters “English, German…” but in Spanish these are lowercase “inglés, alemán…”. But I’m assuming that’s the standard way to write languages in Spanish?

2023-06-06 20:46 UTC, Waxer59 commented on docs/src/content/docs/es/guides/i18n.mdx
> +Starlight proporciona de forma predeterminada traducciones para los textos utilizados en la UI al inglés, alemán, japonés, portugués y español. También damos la bienvenida a [contribuciones para agre
ah yes, in Spanish, the standard way to write the names of the languages is using lower case letters

2023-06-06 22:17 UTC, delucis approved these changes
Thanks again for this PR @Waxer59 💖

2023-06-06 22:21 UTC, merged