Updates internal github actions to the latest versions
withastro/starlight pull request #1569
Opened 2024-02-28 21:14 UTC by martrapp

#### Description

Get rid of those warnings:
![image](https://github.com/withastro/starlight/assets/94928215/1f1e2621-bc20-4b93-8897-3960f64fb102)

2024-02-28 21:15 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Starlight! ✨

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any issues you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🤩

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-02-28 21:16 UTC, astrobot-houston commented
## size-limit report 📦 
| Path          | Size          |
| ------------- | ------------- |
| /index.html   | 5.23 KB (0%)  |
| /_astro/*.js  | 21.54 KB (0%) |
| /_astro/*.css | 13.45 KB (0%) |

2024-02-28 23:50 UTC, kevinzunigacuellar approved these changes
LGTM! Logs are looking nice (no warnings) and majors versions seem to have no breaking changes besides upgrading node 16 to 20.

2024-02-29 14:28 UTC, martrapp commented
I kept actions/labeler@v4 as updating to v5 requires a change of the configuration. This will be a PR on its own.

2024-02-29 14:38 UTC, delucis requested changes
Thanks so much for the careful updates @martrapp!

Just one note from me.

2024-02-29 14:38 UTC, delucis commented on .changeset/fluffy-trains-rest.md
No need for a changeset in this case — none of these impact integration users — so we can remove this.

2024-02-29 16:58 UTC, delucis approved these changes
Thanks again @martrapp — LGTM 🌟

2024-02-29 16:58 UTC, merged