i18n(it): Update `guides/components.mdx`
withastro/starlight pull request #1601
Opened 2024-03-05 16:38 UTC by casungo

#### Description

Updated `guides/components.mdx`

2024-03-06 06:15 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view) and except one small typo in a link, everything looks perfect to me :thumbsup:

2024-03-06 06:15 UTC, HiDeoo commented on docs/src/content/docs/it/guides/components.mdx
> +Specifica la struttura dei tuoi file e directory con una [lista Markdown non ordinata](https://www.markdownguide.org/basic-syzntax/#unordered-lists) all'interno di `<FileTree>`.
```suggestion
Specifica la struttura dei tuoi file e directory con una [lista Markdown non ordinata](https://www.markdownguide.org/basic-syntax/#unordered-lists) all'interno di `<FileTree>`.
```

Small typo leading to a 404

2024-03-06 20:42 UTC, casungo commented on docs/src/content/docs/it/guides/components.mdx
> +Specifica la struttura dei tuoi file e directory con una [lista Markdown non ordinata](https://www.markdownguide.org/basic-syzntax/#unordered-lists) all'interno di `<FileTree>`.
Thanks! fixed now :)

2024-03-07 09:06 UTC, HiDeoo approved these changes
Thanks for the fix :rocket:

2024-03-07 09:09 UTC, merged