[WIP] i18n(pt-br): translating guides/pages file
withastro/starlight pull request #1603
Opened 2024-03-05 21:51 UTC by kayaman

#### Description

- Adding the translation of the `guides/pages.mdx` missing file.

2024-03-09 05:08 UTC, Fryuni requested changes
Thank you for the PR!

Some things to improve:
- There is a missing sentence and an English sentence that was kept around.
- Internal links should always point to the translated pages in the same language, even if the target of the link hasn't been translated yet. You can check those locally by running `CHECK_LINKS=true pnpm build`.
- We translate some terms differently in other pages, so I sent suggestions for consistency
- Some terms that we usually translate elsewhere were not translated

2024-03-15 17:04 UTC, kayaman commented
@Fryuni thank you for the review. I did the requested changes but there's still one issue I wasn't able to solve, as pointed here: https://github.com/withastro/starlight/actions/runs/8299714503/job/22716051747#step:6:484
Do you have a clue, please? Thank you.

2024-03-15 17:24 UTC, kayaman commented
> @Fryuni thank you for the review. I did the requested changes but there's still one issue I wasn't able to solve, as pointed here: https://github.com/withastro/starlight/actions/runs/8299714503/job/22716051747#step:6:484 Do you have a clue, please? Thank you.

I did dig a little more and ended with just one last broken link.

2024-03-16 08:35 UTC, HiDeoo commented on docs/src/content/docs/pt-br/guides/pages.mdx
> +Indica se esta página está usando [conteúdo fallback](/pt-br/guides/i18n/#fallback-content) porque não há tradução para a linguagem atual.
```suggestion
Indica se esta página está usando [conteúdo fallback](/pt-br/guides/i18n/#conteúdo-de-fallback) porque não há tradução para a linguagem atual.
```

> I did dig a little more and ended with just one last broken link.

Thanks for the updates 🙌 

It looks like the last broken link is this one as in `/pt-br/guides/i18n/#fallback-content`, the `fallback-content` does not exist but is instead [`conteúdo-de-fallback`](https://starlight.astro.build/pt-br/guides/i18n/#conte%C3%BAdo-de-fallback) as it's based on the section title which is translated too.

2024-03-16 17:24 UTC, kayaman commented
> > @Fryuni thank you for the review. I did the requested changes but there's still one issue I wasn't able to solve, as pointed here: https://github.com/withastro/starlight/actions/runs/8299714503/job/22716051747#step:6:484 Do you have a clue, please? Thank you.
> 
> 
> 
> I did dig a little more and ended with just one last broken link.

awesome @Fryuni and @HiDeoo ! Thank you for your time reviewing it. I think all tests are fixes now. Thank you so much.

2024-03-18 15:03 UTC, HiDeoo approved these changes
Thanks for fixing the remaining issues. This looks perfect now :thumbsup:

Great job on the translation and the reviews everyone :rocket:

2024-03-18 18:29 UTC, Fryuni approved these changes
Amazing, looking great now!

2024-03-18 18:30 UTC, merged