Add runs-on.com to showcase-sites.astro
withastro/starlight pull request #1617
Opened 2024-03-14 13:56 UTC by crohr

Hello, and thanks for making Starlight! I've been looking for a while for a nice documentation website template, with support for landing pages + blog, and Starlight delivers just that!

The screenshot is from the landing page of [runs-on.com](https://runs-on.com) (which uses the starlight `splash`), but let me know if I should reference another page instead.

I'd really like to be added to the showcase if possible :)

2024-03-14 13:56 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Starlight! ✨

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any issues you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🤩

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-03-16 08:52 UTC, HiDeoo requested changes
Thanks for your contribution to the showcase, amazing addition :star_struck:

One tiny detail, we usually use `800x450` images for the showcase (we are in the process of documenting this process). Would you mind updating the image to that size, e.g. like this one:

![runs-on com](https://github.com/withastro/starlight/assets/494699/d1b83087-5d24-4e0d-aea3-77ba295322fd)

2024-03-18 16:54 UTC, crohr commented
@HiDeoo thanks! I think it should be good now.

2024-03-19 08:30 UTC, HiDeoo approved these changes
Thanks for updating the image, everything looks great! :tada:

2024-03-19 08:38 UTC, merged