Adds custom styles for `<details>` and `<summary>` elements in Markdown content
withastro/starlight pull request #1735
Opened 2024-04-10 16:27 UTC by HiDeoo

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content
- Changes to Starlight code

#### Description

This PR adds custom styles for `<details>` and `<summary>` elements in Markdown content, adresssing the [request](https://github.com/withastro/starlight/discussions/1491#discussioncomment-8889999) in the [built-in components discussion](https://github.com/withastro/starlight/discussions/1491).

Preview playground page: // TODO(HiDeoo) 

The approach used does not add a new `<Details>` component but relies on the native `<details>` and `<summary>` HTML elements, similar to the [Docusaurus approach](https://docusaurus.io/docs/markdown-features#details).

The current design is based on the [Astro Docs](https://docs.astro.build/en/tutorial/0-introduction/1/) custom implementation but the implementation is not exactly identical as I noticed a few minor issues while implementing it (some margins inconsistencies and some border being offset by 1px when toggling the details). 
This PR also adds support for RTL languages, `prefers-reduced-motion` and some minor color adjustments to match the Starlight theme.

One point to note is also the usage of `<details>` in asides, where the styling deviates from Astro Docs as it can lead to some readability issues. I implemented custom variations to address this, but I don't think it looks the best as I did not introduce any new color (which may be needed to make it more appealing) and I'm also not the best when it comes to design decisions.

I reviewed the accessibility of the implementation using this [checklist](https://designsystem.digital.gov/components/accordion/accessibility-tests/) and testing with screen readers but relying on the native elements ensures most of the concerns are addressed out of the box.

2024-04-11 14:58 UTC, HiDeoo commented
Following a Talking and Doc'ing session (April 11, 2024), some very interesting feedback was received from the participants, thank you all for your time and feedback!

One particular piece of feedback from @kevinzunigacuellar  was that it may be difficult to follow if a user is still in a `<details>` or not , specially in nested `<details>`. Discussions about this included the idea of adding some borders to the `<details>` to make it more clear. Here are some screenshots of me playing around with the idea, nothing is final of course and the goal is just to discuss the idea.

### Borders around all `<details>`

Personal opinion: I think this adds a lot of visual noise and importance to the `<details>`.

<img width="1305" alt="Borders around all details" src="https://github.com/withastro/starlight/assets/494699/553a3b01-7c65-49c1-b893-489f0419578b">

### Borders only around nested `<details>`

<img width="1308" alt="Borders only around nested details" src="https://github.com/withastro/starlight/assets/494699/d461d137-432d-4e99-b5d8-d86af6283546">

### Slightly dimmed borders around nested `<details>`

<img width="1308" alt="Slightly dimmed borders around nested details" src="https://github.com/withastro/starlight/assets/494699/6287d24b-94e7-4c33-bd43-45829e3eba7e">

2024-04-12 13:01 UTC, HiDeoo commented
Sharing here another great approach to the design by @delucis 

<img width="557" alt="image" src="https://github.com/withastro/starlight/assets/494699/c338b107-9db9-49c5-9b7f-c6cb0de2fd14">

<img width="738" alt="image" src="https://github.com/withastro/starlight/assets/494699/8c07dc57-6001-4f23-aea2-0d5c2e296402">

The preview is available here: https://starlight-git-chris-details-dabbling-astrodotbuild.vercel.app/reference/details/

2024-04-22 09:45 UTC, HiDeoo commented
I updated the PR to use Chris's design. I personally prefer it but as it's now part of the history, we can easily switch between the two if ever needed. My main remaining concern may be the visibility of the left border in light mode.

In a separate commit, I also added a suggestion from Sarah to move the marker to the left to emphasize that these are clickable which was one of the main feedback from the previous post. Same, this can be easily reverted now during iterations.

2024-05-03 15:07 UTC, HiDeoo commented
Updated the PR and tweaked border colors: the `<details>` border color is now more "vivid" compared to the one from a blockquote or a `<Steps>` component to emphasize that it's an interactive element. Hovering and the opened state borders are also more "vivid" now to match this change.

Hovering an opened `<details>` element will now also change the border color to a different color to still indicate that it's clickable.

And finally, I fixed a marker position issue with long summaries due to MDX wrapping the summary in a `<p>` tag.

2024-05-15 06:54 UTC, subframe7536 commented on packages/starlight/style/markdown.css
> +	display: none;
`display: none` is invalid for summary marker, please add `list-style: none` instead

2024-05-16 20:20 UTC, delucis requested changes
Thanks again for the work on this @HiDeoo!

I’ll summarise again the couple of changes that we discussed and I pushed directly:
- border is now 2px instead of 1px, matching the `<Tabs>` component thickness
- hover styling only applies when hovering `<summary>` on expanded `<details>` — this helps avoid a slightly chaotic/flickering feeling with the border colour changing rapidly as user’s move over details
- hover colour is now a more bold accent like `<Tabs>` uses for selected tabs

Other than that I think we’re more or less there! I left a couple of notes on the docs and some CSS, but then I think we should be good to clean up the test page.

We’ll probably also need to bump up the CSS size-limit budget.

2024-05-16 20:20 UTC, delucis commented on docs/src/content/docs/guides/authoring-content.md
> +The user can reveal further information with an interaction to toggle the visibility of the content.
This sentence was maybe saying the same thing twice a bit: “reveal further information” and “toggle the visibility of the content”.

I think we can maybe boil it down to this?

```suggestion
Users can click a short summary to expand and view the full content.
```

2024-05-16 20:20 UTC, delucis commented on docs/src/content/docs/guides/authoring-content.md
> +Starlight does not provide a custom Markdown syntax for details, but you can use the standard HTML `<details>` and `<summary>` elements to create them while authoring your Markdown content.
I think we can describe the positive “what to do” here without mentioning what we don’t do. I do not _love_ “widget” as a word here, but it does appear to be what MDN uses, so maybe it’s OK? (And does work better than “element”, “component”, or “pattern”… any other ideas?)

```suggestion
Use the standard HTML [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) and [`<summary>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary) elements in your Markdown content to create a disclosure widget.
```

2024-05-16 20:20 UTC, delucis commented on docs/src/content/docs/guides/authoring-content.md
> +You can nest any other Markdown content types inside a `<details>` element.
Maybe “syntax” works better here?

```suggestion
You can nest any other Markdown syntax inside a `<details>` element.
```

2024-05-16 20:20 UTC, delucis commented on docs/src/content/docs/guides/authoring-content.md
> +```
Guess we need to make sure the demo content is also just right 😅 

Just a small English grammar detail here:

````suggestion
<details>
<summary>Where and when is the Andromeda constellation most visible?</summary>

The [Andromeda constellation](<https://en.wikipedia.org/wiki/Andromeda_(constellation)>) is most visible in the night sky during the month of November at latitudes between `+90°` and `−40°`.

</details>

```md
<details>
<summary>Where and when is the Andromeda constellation most visible?</summary>

The [Andromeda constellation](<https://en.wikipedia.org/wiki/Andromeda_(constellation)>) is most visible in the night sky during the month of November at latitudes between `+90°` and `−40°`.

</details>
```
````

2024-05-17 16:46 UTC, sarah11918 approved these changes
Approving for docs!

2024-05-17 16:54 UTC, delucis approved these changes
Thank you for working through the different iterations and rolling with the changes I kept throwing at you @HiDeoo! 🎉 

It will be nice to see these updated and in-use in Astro’s docs soon too.

2024-05-17 16:55 UTC, merged