i18n(tr): update `getting-started.mdx` file
withastro/starlight pull request #1792
Opened 2024-04-28 12:46 UTC by erkanaltinors

**What kind of changes does this PR include?**

Updates of Starlight docs site content

**Description**

This pull request updates translated in Turkish getting-started.mdx file in project.

2024-04-28 12:47 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                               | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| tr     | [getting-started.mdx](https://github.com/withastro/starlight/blob/8ee97d28706c869b67348176ea640f36ce67fc42/docs%2Fsrc%2Fcontent%2Fdocs%2Ftr%2Fgetting-started.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-04-29 09:12 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left a few minor suggestions but overall this is looking really good! :thumbsup:

2024-05-01 10:45 UTC, erkanaltinors commented on docs/src/content/docs/tr/getting-started.mdx
>  <TabItem label="npm">
Hello @HiDeoo , thanks for your kins response. I've removed comments for each installation commands with my [latest commit](https://github.com/withastro/starlight/pull/1792/commits/f828c317ddad77056119178dba205d99c0e60c55).

2024-05-01 11:18 UTC, HiDeoo reviewed
Thanks for the update, addresses perfectly all my comments 👍 

Unfortunately, this would need 1 more update as Starlight 0.22 was released yesterday and in the process, this page has been updated with [these changes](https://github.com/withastro/starlight/pull/640/files#diff-130a89ed8dd4068e1a366e0a6a31adb124cc60387ba42faadf457e83f9583948).
Fortunately, the changes are minimal and the idea is basically to add `syncKey="pkg"` to the 3 `<Tabs>` components in this page.

2024-05-01 14:14 UTC, HiDeoo approved these changes
This looks perfect, thanks a lot for the updates :raised_hands:

2024-05-01 14:15 UTC, merged