i18n(es): update `guides/components` and add `syncKey` to various pages
withastro/starlight pull request #1818
Opened 2024-05-01 23:49 UTC by dreyfus92

#### Description

- Closes # N/A
- What does this PR change? Give us a brief description.

This PR updates the spanish version of the `guides/components.mdx` based on this commit #640.

It also adds the `syncKey` prop to the French version of the following pages as it felt small enough to be done in one go:

- `getting-started.mdx`
- `guides/css-and-tailwind.mdx`
- `guides/customization.mdx`

2024-05-01 23:50 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                                 | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| es     | [getting-started.mdx](https://github.com/withastro/starlight/blob/509bb9ebf6aa4afc2a94b774047816f8e213a224/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fgetting-started.mdx)                   | Localization changed, will be marked as complete.  |
| es     | [guides/components.mdx](https://github.com/withastro/starlight/blob/509bb9ebf6aa4afc2a94b774047816f8e213a224/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fguides%2Fcomponents.mdx)             | Localization changed, will be marked as complete.  |
| es     | [guides/css-and-tailwind.mdx](https://github.com/withastro/starlight/blob/509bb9ebf6aa4afc2a94b774047816f8e213a224/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fguides%2Fcss-and-tailwind.mdx) | Localization changed, will be marked as complete.  |
| es     | [guides/customization.mdx](https://github.com/withastro/starlight/blob/509bb9ebf6aa4afc2a94b774047816f8e213a224/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fguides%2Fcustomization.mdx)       | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-02 07:48 UTC, HiDeoo requested changes
Thanks for the update :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). Left a tiny suggestion, but otherwise, this looks good to me. :thumbsup:

2024-05-02 07:48 UTC, HiDeoo commented on docs/src/content/docs/es/guides/components.mdx
> +_Some exoplanets:_
```suggestion
_Algunos exoplanetas:_
```

Probably forgot in the process

2024-05-02 07:56 UTC, dreyfus92 commented
Thanks for the review! 😁

2024-05-02 08:11 UTC, HiDeoo approved these changes
Thanks for the fast update 👍

2024-05-02 08:14 UTC, merged