i18n(zh-cn): Update docs about synced-tabs
withastro/starlight pull request #1834
Opened 2024-05-07 08:06 UTC by liruifengv

#### Description

- Update docs about synced-tabs
- https://github.com/withastro/starlight/pull/640

2024-05-07 08:07 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                                    | Note                                               |
| ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [getting-started.mdx](https://github.com/withastro/starlight/blob/dd5bc9d6b81409cb8195ed48100aeea41bb19ffc/docs%2Fsrc%2Fcontent%2Fdocs%2Fzh-cn%2Fgetting-started.mdx)                   | Localization changed, will be marked as complete.  |
| zh-cn  | [guides/css-and-tailwind.mdx](https://github.com/withastro/starlight/blob/dd5bc9d6b81409cb8195ed48100aeea41bb19ffc/docs%2Fsrc%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fcss-and-tailwind.mdx) | Localization changed, will be marked as complete.  |
| zh-cn  | [guides/customization.mdx](https://github.com/withastro/starlight/blob/dd5bc9d6b81409cb8195ed48100aeea41bb19ffc/docs%2Fsrc%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fcustomization.mdx)       | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-08 01:27 UTC, huyikai reviewed
LGTM.

2024-05-08 06:47 UTC, HiDeoo requested changes
Thanks for the update, left a small suggestion to fix a sync issue but other than that, looks perfect to me 👍

2024-05-08 06:47 UTC, HiDeoo commented on docs/src/content/docs/zh-cn/guides/customization.mdx
>    <TabItem label=" frontmatter ">
```suggestion
  <TabItem label="Frontmatter ">
```

To make sure the label are exactly identical and sync properly.

2024-05-08 07:22 UTC, HiDeoo approved these changes
Thanks for the fast update :thumbsup:

2024-05-08 07:27 UTC, merged