i18n(tr): update `authoring-content.md`
withastro/starlight pull request #1887
Opened 2024-05-17 12:49 UTC by erkanaltinors

What kind of changes does this PR include?

Updates of Starlight docs site content

Description

This pull request updates translated in Turkish authoring-content.md file in project.

2024-05-17 12:49 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                                 | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| tr     | [guides/authoring-content.md](https://github.com/withastro/starlight/blob/f3a0d6604803dc946a2727455bc691cb7e750fe3/docs%2Fsrc%2Fcontent%2Fdocs%2Ftr%2Fguides%2Fauthoring-content.md) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-17 21:08 UTC, delucis requested changes
Hi @erkanaltinors — this looks fantastic. I can’t review the language in detail as I don’t speak Turkish, but I went through the translation and the English version side by side and everything seems great.

One thing — today we added a small new section to this page about “Details” — <https://starlight.astro.build/guides/authoring-content/#details>:

https://github.com/withastro/starlight/blob/70f12fc34ff1eb2ce451c118764b10481c2346b9/docs/src/content/docs/guides/authoring-content.md?plain=1#L364-L387

Would you be able to also add this to this PR? Sorry I didn’t pay attention that this page was translated otherwise I would have merged this first, so that our translation tracker could follow what was happening.

2024-05-18 08:33 UTC, erkanaltinors commented
Hi @delucis , I've added details section.

2024-05-18 13:44 UTC, delucis approved these changes
Fantastic! Thank you for taking care of that @erkanaltinors 🌟

2024-05-18 13:45 UTC, merged