i18n(tr): update `components.md` file
withastro/starlight pull request #1889
Opened 2024-05-17 14:27 UTC by erkanaltinors

What kind of changes does this PR include?

Updates of Starlight docs site content

Description

This pull request updates translated in Turkish `components.md` file in project.

2024-05-17 14:27 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                     | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| tr     | [guides/components.mdx](https://github.com/withastro/starlight/blob/5b275481cb7e8bad06782f225b60139122602902/docs%2Fsrc%2Fcontent%2Fdocs%2Ftr%2Fguides%2Fcomponents.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-18 10:09 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left a few tiny  suggestions but this is looking pretty great :thumbsup:

2024-05-18 10:09 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/components.mdx
> +	<TabItem label="Yıldızlar" icon="star">Sirius, Vega, Betelgeuse</TabItem>
I cannot leave a comment for the sentences above the example but it looks like this paragraph contains a few issues:

- The "You can display a tabbed interface using the `<Tabs>` and `<TabItem>` components." is in English.
- It's missing the `icon` attribute description and link

Would you mind taking a look at it and updating it?

2024-05-18 10:09 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/components.mdx
> +Ara bölümler (ayrıca "uyarı" ve "açıklama balonu" olarak da bilinir), sayfanın ana içeriği ile birlikte ikincil bilgi göstermek için kullanışlıdır.
```suggestion
Ara bölümler (ayrıca "uyarı" ve "açıklama balonu" olarak da bilinir), sayfanın ana içeriği ile birlikte ikincil bilgi göstermek için kullanışlıdır.

```

To match the English version

2024-05-18 10:09 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/components.mdx
> +<Aside type="tip">
```suggestion
<Aside type="tip">

```

Just to match the English version too

2024-05-18 10:09 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/components.mdx
> +Starlight also provides a custom syntax for rendering asides in Markdown and MDX as an alternative to the `<Aside>` component.
```suggestion
```

Probably something missed

2024-05-18 10:09 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/components.mdx
> +Her aşamasının açıkça belirtilmeye ihtiyaç duyan çok karmaşık adım adım rehberleri oluşturmak için kullanışlıdır.
```suggestion
`<Steps>` bileşenini numaralanmış görevler listesini biçimlendirmek için kullanın.
Her aşamasının açıkça belirtilmeye ihtiyaç duyan çok karmaşık adım adım rehberleri oluşturmak için kullanışlıdır.
```

To match the english version

2024-05-18 10:09 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/components.mdx
> +`<Steps>` bileşeni içerisinde tüm olağan Markdown sözdizimi uygulanabilir.
```suggestion
Standart Markdown sıralanmış listesini `<Steps>` bileşeni ile sarmalayın.
`<Steps>` bileşeni içerisinde tüm olağan Markdown sözdizimi uygulanabilir.
```

Same as above

2024-05-18 10:09 UTC, HiDeoo commented on docs/src/content/docs/tr/guides/components.mdx
> +`size` ve `color` nitelikleri ikonun görünümünü CSS birimleri ve renk değerleri ile ayarlamak için kullanılabilir.
```suggestion

Her `<Icon>` [`name`](#tüm-i̇konlar) değerine ihtiyaç duyar ve isteğe bağlı olarak `label` eklenebilir.
`size` ve `color` nitelikleri ikonun görünümünü CSS birimleri ve renk değerleri ile ayarlamak için kullanılabilir.
```

2024-05-18 10:53 UTC, erkanaltinors commented
@HiDeoo I've applied all suggessted changes in last commit.

2024-05-18 10:57 UTC, HiDeoo approved these changes
> @HiDeoo I've applied all suggessted changes in last commit.

Perfect and super fast, thanks a lot for another great translation :raised_hands:

2024-05-18 11:00 UTC, merged