i18n(pt-PT): update outdated pages
withastro/starlight pull request #1945
Opened 2024-05-30 08:26 UTC by rgilsimoes

#### Description

- Updated getting-started.mdx community-content.mdx and plugins.mdx

2024-05-30 08:27 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                                            | Note                                               |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| pt-pt  | [getting-started.mdx](https://github.com/withastro/starlight/blob/6947cd8c02de6a545493fd50c61d22c34c1c6f24/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fgetting-started.mdx)                           | Localization changed, will be marked as complete.  |
| pt-pt  | [resources/community-content.mdx](https://github.com/withastro/starlight/blob/6947cd8c02de6a545493fd50c61d22c34c1c6f24/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fresources%2Fcommunity-content.mdx) | Localization changed, will be marked as complete.  |
| pt-pt  | [resources/plugins.mdx](https://github.com/withastro/starlight/blob/6947cd8c02de6a545493fd50c61d22c34c1c6f24/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fresources%2Fplugins.mdx)                     | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-06-03 18:52 UTC, delucis requested changes
Thank you for the update @rgilsimoes! Just spotted a couple of small typos.

2024-06-03 18:52 UTC, delucis commented on docs/src/content/docs/pt-pt/resources/community-content.mdx
> +				'Inclua a documentação Startligth num projecto Next.js através de proxies',
Typo here I think
```suggestion
				'Inclua a documentação Starlight num projecto Next.js através de proxies',
```

2024-06-03 18:52 UTC, delucis commented on docs/src/content/docs/pt-pt/resources/community-content.mdx
> +				'Configurar o Startlight como uma sub-directoria dentro de um site Next.js',
And here
```suggestion
				'Configurar o Starlight como uma sub-directoria dentro de um site Next.js',
```

2024-06-03 18:52 UTC, delucis commented on docs/src/content/docs/pt-pt/resources/community-content.mdx
> +				'Neste video eu abordo o que torna o Starligh tão porreiro e porque razão deve experimentá-lo no seu próximo projecto.',
And also here

```suggestion
				'Neste video eu abordo o que torna o Starlight tão porreiro e porque razão deve experimentá-lo no seu próximo projecto.',
```

2024-06-03 20:07 UTC, rgilsimoes commented
> Thank you for the update @rgilsimoes! Just spotted a couple of small typos.

Darn... dislexia hit me hard on Starlight :-)

2024-06-03 22:42 UTC, delucis approved these changes
English spelling sure doesn't help! 

Thank you @rgilsimoes 💖

2024-06-03 22:42 UTC, merged