Add how2neovim to showcase
withastro/starlight pull request #1981
Opened 2024-06-07 16:13 UTC by finnala

#### Description

Adds [how2neovim.io](how2neovim.io) to the showcase section.

2024-06-07 16:14 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Starlight! ✨

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any issues you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🤩

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-06-12 08:01 UTC, HiDeoo requested changes
Thanks for your contribution to the showcase :raised_hands:

It looks like the provided image contains some sort of top and bottom borders:

<img width="865" alt="image" src="https://github.com/withastro/starlight/assets/494699/e8505f43-5400-48bb-9471-3628b9117a73">

Would you mind updating it to one without the border, e.g. this one:

![how2neovim io](https://github.com/withastro/starlight/assets/494699/ef90ee1a-dfa3-42e6-901f-f6252f94f279)

Except for that tiny border, this looks perfect to me 🌟

2024-06-12 10:45 UTC, finnala commented
Hi @HiDeoo apologies for that - have updated the image. 

Hope it is all good.

2024-06-12 10:56 UTC, delucis approved these changes
Thanks for the fix @finnala! Looks good now 🚀

2024-06-12 11:16 UTC, merged