i18n(es): update `i18n`
withastro/starlight pull request #1996
Opened 2024-06-11 14:41 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Updates `i18n` based on this commit ee0cd38a1fae31717fe820e779baeabe693cd67a

2024-06-11 14:42 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                         | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| es     | [guides/i18n.mdx](https://github.com/withastro/starlight/blob/ff6fd7455683bd4d3ecb9f70374bfcb5c3d65108/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fguides%2Fi18n.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-06-12 07:17 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view) and except for 1 small change, this looks good to me.

2024-06-12 07:17 UTC, HiDeoo commented on docs/src/content/docs/es/guides/i18n.mdx
> +Para escenarios de i18n más avanzados, Starlight también admite la configuración de internacionalizaciónutlizando la [opción `i18n` de Astro](https://docs.astro.build/es/guides/internationalization/#
```suggestion
Para escenarios de i18n más avanzados, Starlight también admite la configuración de internacionalizaciónutlizando la [opción `i18n` de Astro](https://docs.astro.build/es/guides/internationalization/#configuración-de-rutas-i18n).
```

2024-06-12 07:17 UTC, HiDeoo commented on docs/src/content/docs/es/guides/i18n.mdx
> +<a href={`/${Astro.currentLocale}/about`}>About</a>
Would it make sense to translate the link "About" text?

2024-06-12 14:00 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/i18n.mdx
> +<a href={`/${Astro.currentLocale}/about`}>About</a>
```suggestion
<a href={`/${Astro.currentLocale}/about`}>Acerca</a>
```

2024-06-13 10:06 UTC, HiDeoo approved these changes
Thanks for updating the PR :thumbsup: Looks perfect to me.

2024-06-13 10:10 UTC, merged