i18n(es): update `sidebar`
withastro/starlight pull request #1997
Opened 2024-06-11 14:45 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Updates `sidebar` based on this commit dd64836af45f33df4a99ab864eabb91fc9b8e204

2024-06-11 14:46 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                               | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| es     | [guides/sidebar.mdx](https://github.com/withastro/starlight/blob/f1cb9ae1a04f054da0d23bfe093c5d8a6d37a6de/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fguides%2Fsidebar.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-06-12 07:20 UTC, HiDeoo requested changes
Thanks for the update :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view) and except for 1 missing change, this looks good to me.

2024-06-12 07:20 UTC, HiDeoo commented on docs/src/content/docs/es/guides/sidebar.mdx
>  ### Variantes de insignia
I think this is missing the heading change with the new "and custom styling" part.

2024-06-14 17:44 UTC, dreyfus92 commented
Nice catch and thank you @HiDeoo for your review 😁

2024-06-15 07:41 UTC, HiDeoo approved these changes
Thanks for the fix :raised_hands:

2024-06-15 07:49 UTC, merged