i18n(fr): Update `resources/community-content.mdx` from #2049
withastro/starlight pull request #2073
Opened 2024-07-01 15:52 UTC by thomasbnt

#### Description
 Update `resources/community-content.mdx` from #2049
- i18n(fr)

2024-07-01 15:53 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                         | Note                                               |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| fr     | [resources/community-content.mdx](https://github.com/withastro/starlight/blob/65c84a9c2bdcd7542a3bf16630a67bbe71796afa/docs%2Fsrc%2Fcontent%2Fdocs%2Ffr%2Fresources%2Fcommunity-content.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-02 13:38 UTC, pioupia approved these changes
LGTM!

2024-07-02 17:41 UTC, HiDeoo requested changes
Thanks for the update 🙌 

I tweaked the sentence a little bit to remove the remaining English `'s`. Let me know what you think about the change.

2024-07-02 17:41 UTC, HiDeoo commented on docs/src/content/docs/fr/resources/community-content.mdx
> +				"Chris, le créateur du framework Astro's Starlight, explique comment le mettre en place pour un nouveau site web d'emoji-blast. 🌟 🎇",
```suggestion
				"Chris, le créateur du thème de documentation Starlight pour Astro, m'aide à le configurer pour le nouveau site web d'emoji-blast. 🌟 🎇",
```

The English `'s` in `Astro's Starlight` was remaining so I tweaked the sentence a bit to remove it and uses the same description ("thème de documentation") that we are using on the French [version](https://starlight.astro.build/getting-started/) of the getting started guide.

2024-07-02 20:12 UTC, thomasbnt commented
> Thanks for the update 🙌
> 
> I tweaked the sentence a little bit to remove the remaining English `'s`. Let me know what you think about the change.

Thanks for the review @HiDeoo !

2024-07-03 06:44 UTC, HiDeoo approved these changes
Amazing, thanks for the translation and the review :star2:

2024-07-03 06:49 UTC, merged