i18n(es): update `sidebar`
withastro/starlight pull request #2128
Opened 2024-07-12 17:17 UTC by dreyfus92

#### Description

- Closes # N/A
- What does this PR change? Give us a brief description.
Updates `sidebar` based on this commit eeba06ea7df962e8f0520e145d28b8c17cd32c18

2024-07-12 17:18 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                               | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| es     | [guides/sidebar.mdx](https://github.com/withastro/starlight/blob/d094e14c6f55033e959a90228934194f426fb43a/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fguides%2Fsidebar.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-15 14:16 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left a few comments/suggestions but overall the translation is looking really great :thumbsup:

2024-07-15 14:16 UTC, HiDeoo commented on docs/src/content/docs/es/guides/sidebar.mdx
> +						'constellations/ursa-menor',
```suggestion
						'constellations/andromeda',
						'constellations/orion',
						'constellations/ursa-minor',						
```

The existing translations did not translate slugs but only titles so we should keep it consistent (or change that everywhere on the page if you prefer, your call).

2024-07-15 14:16 UTC, HiDeoo commented on docs/src/content/docs/es/guides/sidebar.mdx
> +					slug: 'stars/sirius',
The highlight of this code block should be updated from `10` to `9` to match this change.

2024-07-15 14:16 UTC, HiDeoo commented on docs/src/content/docs/es/guides/sidebar.mdx
> +
The first code block of the "Collapsing groups" section is missing a [change](https://github.com/withastro/starlight/pull/1874/files#diff-f2469f170cfdf3bc0930d7a06705fe128dd16032760fff8618641d1dc5d5edadL444-L447) but I cannot suggest a change for it:


```diff
-			items: [
-				{ label: 'Andrómeda', link: '/constellations/andromeda/' },
-				{ label: 'Orion', link: '/constellations/orion/' },
-			],
+			items: ['constellations/andromeda', 'constellations/orion'],
```

2024-07-16 16:29 UTC, dreyfus92 commented
Thank you for the review @HiDeoo 😁

2024-07-16 17:18 UTC, HiDeoo approved these changes
Thanks for the update, this is looking great :raised_hands: (I removed duplicated `items` from the last section as it was a very minor edit, hope you don't mind)

2024-07-16 17:20 UTC, merged