i18n(it): Updates `guides/i18n.mdx`
withastro/starlight pull request #2192
Opened 2024-08-09 21:07 UTC by casungo

#### Description

Updates `guides/i18n.mdx`

2024-08-09 21:08 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                         | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| it     | [guides/i18n.mdx](https://github.com/withastro/starlight/blob/a78ef0abe79bd1922ecdcb4c69cdecaffa316943/docs%2Fsrc%2Fcontent%2Fdocs%2Fit%2Fguides%2Fi18n.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-10 09:29 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view) and this looks great to me! I only left a suggestion that should fix the links validation issue due to an invalid anchor.

2024-08-10 09:29 UTC, HiDeoo commented on docs/src/content/docs/it/guides/i18n.mdx
> +Se hai bisogno di personalizzare il titolo per ogni locale, puoi passare un oggetto a [`title`](/it/reference/configuration/#title-required) nelle opzioni di Starlight:
```suggestion
Se hai bisogno di personalizzare il titolo per ogni locale, puoi passare un oggetto a [`title`](/it/reference/configuration/#title-obbligatorio) nelle opzioni di Starlight:
```

2024-08-13 09:05 UTC, delucis approved these changes
LGTM!

2024-08-13 09:05 UTC, merged