i18n(it): Updates `reference/frontmatter.md`
withastro/starlight pull request #2194
Opened 2024-08-09 21:10 UTC by casungo

#### Description

Updates `reference/frontmatter.md`

2024-08-09 21:10 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                           | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| it     | [reference/frontmatter.md](https://github.com/withastro/starlight/blob/4b10626afd982c96c18c10d05f4ec32cdd732319/docs%2Fsrc%2Fcontent%2Fdocs%2Fit%2Freference%2Ffrontmatter.md) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-10 09:37 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). This looks great to me, I only have a few suggestions:

- I suggested a change to fix the link issue preventing the build to pass.
- It looks like [this change](https://github.com/withastro/starlight/pull/1530/files#diff-6d478912950527786985d16b5fef998fc9a98ffc282f20ebe557b822d0e717bd) is missing.

2024-08-12 10:16 UTC, delucis commented
> I suggested a change to fix the link issue preventing the build to pass.

Looks like this suggestion went missing? I don’t see it in this PR.

2024-08-12 10:26 UTC, delucis commented on docs/src/content/docs/it/reference/frontmatter.md
> +Imposta se questa pagina deve essere considerata una bozza e non essere inclusa nelle [build di produzione](https://docs.astro.build/en/reference/cli-reference/#astro-build) e nei [gruppi di link aut
This link needs fixing here to point to the Italian translation:

```suggestion
Imposta se questa pagina deve essere considerata una bozza e non essere inclusa nelle [build di produzione](https://docs.astro.build/en/reference/cli-reference/#astro-build) e nei [gruppi di link autogenerati](/it/guides/sidebar/#gruppi-generati-automaticamente). Imposta su `true` per contrassegnare una pagina come bozza e renderla visibile solo durante lo sviluppo.
```

2024-08-12 10:30 UTC, delucis reviewed
As @HiDeoo mentioned, there is still this one small update needed: https://github.com/withastro/starlight/pull/1530/files#diff-6d478912950527786985d16b5fef998fc9a98ffc282f20ebe557b822d0e717bd

2024-08-12 15:19 UTC, delucis approved these changes
Thanks for the update @casungo!

2024-08-12 15:20 UTC, merged