i18n(es): translate `card-grids`
withastro/starlight pull request #2399
Opened 2024-09-24 04:11 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Translates `card-grids` to spanish

2024-09-24 04:12 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                             | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| es     | [components/card-grids.mdx](https://github.com/withastro/starlight/blob/4599efb4260911ad16985053742c5f413768e564/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fcomponents%2Fcard-grids.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-24 08:46 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left a few comments and suggestions but everything else looks good to me.

2024-09-24 08:46 UTC, HiDeoo commented on docs/src/content/docs/es/components/card-grids.mdx
> +	<Card title="Stars" icon="star">
```suggestion
	<Card title="Estrellas" icon="star">
```

I guess we can use the previous translation from the old component documentation?

2024-09-24 08:46 UTC, HiDeoo commented on docs/src/content/docs/es/components/card-grids.mdx
> +	<Card title="Moons" icon="moon">
```suggestion
	<Card title="Lunas" icon="moon">
```

2024-09-24 08:46 UTC, HiDeoo commented on docs/src/content/docs/es/components/card-grids.mdx
> +	<Card title="Other feature" icon="information">
We should be able to translate both titles in this example.

2024-09-24 08:46 UTC, HiDeoo commented on docs/src/content/docs/es/components/card-grids.mdx
> +```mdx {3,6}
```suggestion
```mdx {3,9}
```

To match the new formatting

2024-09-24 19:59 UTC, dreyfus92 commented
Thanks @HiDeoo 🫡

2024-09-25 06:54 UTC, HiDeoo approved these changes
Thanks for updating the PR :thumbsup:

2024-09-25 06:57 UTC, merged