i18n(es): translate `cards`
withastro/starlight pull request #2400
Opened 2024-09-24 04:47 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Translates `cards` to spanish

2024-09-24 04:47 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                   | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| es     | [components/cards.mdx](https://github.com/withastro/starlight/blob/e77180f001057a9dec0143d279395609828560f4/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fcomponents%2Fcards.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-26 08:56 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left a few suggestions to translate the example titles but other than that, everything looks good to me.

2024-09-26 08:56 UTC, HiDeoo commented on docs/src/content/docs/es/components/cards.mdx
> +<Card slot="preview" title="Moons" icon="moon">
```suggestion
<Card slot="preview" title="Lunas" icon="moon">
```

We can translate the title in this preview but not sure about my suggestion.

2024-09-26 08:56 UTC, HiDeoo commented on docs/src/content/docs/es/components/cards.mdx
> +<Card title="Stars" icon="star">
```suggestion
<Card title="Estrellas" icon="star">
```

Same here

2024-09-26 08:56 UTC, HiDeoo commented on docs/src/content/docs/es/components/cards.mdx
> +{% card title="Stars" icon="star" %}
```suggestion
{% card title="Estrellas" icon="star" %}
```

2024-09-26 08:56 UTC, HiDeoo commented on docs/src/content/docs/es/components/cards.mdx
> +<Card slot="preview" title="Stars" icon="star">
```suggestion
<Card slot="preview" title="Estrellas" icon="star">
```

2024-09-27 03:43 UTC, dreyfus92 commented
Thanks @HiDeoo for the review 🫡

2024-09-27 07:30 UTC, HiDeoo approved these changes
Thanks for the updating the PR, looks great to me now :star2:

2024-09-27 07:33 UTC, merged