i18n(es): translate `code`
withastro/starlight pull request #2401
Opened 2024-09-24 06:42 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Translates `code` to spanish

2024-09-24 06:43 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                 | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| es     | [components/code.mdx](https://github.com/withastro/starlight/blob/7b2a09b89a902ef8d2b988ab58d0a65819cd276c/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fcomponents%2Fcode.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-24 08:37 UTC, HiDeoo requested changes
Thanks for updating this page :thumbsup:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). Looks like we can translate a few examples that currently are not translated, but the rest of the content looks good to me.

2024-09-24 08:37 UTC, HiDeoo commented on docs/src/content/docs/es/components/code.mdx
> +Hello from **space**!`}
We can safely translate this example.

2024-09-24 08:37 UTC, HiDeoo commented on docs/src/content/docs/es/components/code.mdx
> +export const exampleCode = `console.log('This could come from a file or CMS!');`;
We could also translate the `exampleCode` in this example.

2024-09-24 08:37 UTC, HiDeoo commented on docs/src/content/docs/es/components/code.mdx
> +export const highlights = ['file', 'CMS'];
And I assume the `highlights` may need to be updated based on the `exampleCode` changes.

2024-09-25 06:08 UTC, dreyfus92 commented
Thanks again @HiDeoo 🫡

2024-09-25 06:44 UTC, HiDeoo reviewed
Looks like only the MDX example was updated but not the Markdoc one and the preview. I'll use your translation to update these myself so we can merge the PR.

2024-09-25 06:44 UTC, HiDeoo commented on docs/src/content/docs/es/components/code.mdx
> +   code="console.log('This could come from a file or CMS!');"
```suggestion
   code="console.log('¡Esto podría provenir de un archivo o CMS!');"
```

2024-09-25 06:44 UTC, HiDeoo commented on docs/src/content/docs/es/components/code.mdx
> +   meta="'file' 'CMS'" /%}
```suggestion
   meta="'archivo' 'CMS'" /%}
```

2024-09-25 06:44 UTC, HiDeoo commented on docs/src/content/docs/es/components/code.mdx
> +export const exampleCode = `console.log('This could come from a file or CMS!');`;
```suggestion
export const exampleCode = `console.log('¡Esto podría provenir de un archivo o CMS!');`;
```

2024-09-25 06:44 UTC, HiDeoo commented on docs/src/content/docs/es/components/code.mdx
> +export const highlights = ['file', 'CMS'];
```suggestion
export const highlights = ['archivo', 'CMS'];
```

2024-09-25 06:48 UTC, HiDeoo approved these changes
Thanks for updating the examples, looks great to me :raised_hands:

2024-09-25 06:51 UTC, merged