i18n(es): translate `file-tree`
withastro/starlight pull request #2402
Opened 2024-09-24 07:10 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Translates `file-tree` to spanish

2024-09-24 07:10 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                           | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| es     | [components/file-tree.mdx](https://github.com/withastro/starlight/blob/f82ecfeb82376386c59fe4a0320c6db94e1bb139/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fcomponents%2Ffile-tree.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-24 08:31 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left 1 comment regarding an example that could be translated but other than that, the translation looks good to me.

2024-09-24 08:31 UTC, HiDeoo commented on docs/src/content/docs/es/components/file-tree.mdx
> +- astro.config.mjs an **important** file
We can safely translate the "an important file" comment in the preview.

2024-09-24 08:31 UTC, HiDeoo commented on docs/src/content/docs/es/components/file-tree.mdx
> +    - Header.astro an **important** file
Same comment for the 3 instances in this example.

2024-09-25 06:10 UTC, dreyfus92 commented
Nice catch @HiDeoo, all suggestions have been applied 😁

2024-09-25 06:35 UTC, HiDeoo approved these changes
Thanks for the fixes, looks perfect to me now :rocket:

2024-09-25 06:38 UTC, merged