i18n(es): translate `components/icons`
withastro/starlight pull request #2403
Opened 2024-09-24 07:44 UTC by dreyfus92

#### Description

- What does this PR change? Give us a brief description.
Translate `components/icons` to spanish.

2024-09-24 07:45 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                   | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| es     | [components/icons.mdx](https://github.com/withastro/starlight/blob/ea6249323dd6989fbe49d679decff05eceb87f51/docs%2Fsrc%2Fcontent%2Fdocs%2Fes%2Fcomponents%2Ficons.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-24 07:47 UTC, dreyfus92 commented on docs/src/content/docs/es/components/icons.mdx
> +Un icono requiere un [`name`](#name) establecido en [uno de los iconos integrados de Starlight](/reference/icons/#todos-los-iconos) y opcionalmente puede incluir un [`label`](#label) para proporciona
```suggestion
Un icono requiere un [`name`](#name) establecido en [uno de los iconos integrados de Starlight](/es/reference/icons/#todos-los-iconos) y opcionalmente puede incluir un [`label`](#label) para proporcionar contexto a los lectores de pantalla.
```

2024-09-26 09:03 UTC, HiDeoo requested changes
Thanks for the translation :thumbsup:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left a comment regarding a missing translation but everything else looks good to me.

2024-09-27 03:46 UTC, dreyfus92 commented
Thanks again @HiDeoo 😁

2024-09-27 07:36 UTC, HiDeoo approved these changes
Thanks for translating the remaining labels :raised_hands:

2024-09-27 07:39 UTC, merged