i18n(id): Update i18n.mdx translation
withastro/starlight pull request #2440
Opened 2024-10-05 13:35 UTC by iyyafi

#### Description
- Update ID translation guides for i18n.mdx file 

##### PS: I am participating in Hacktoberfest. Please add hacktoberfest-accepted label in this PR. Thank you

2024-10-05 13:35 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                         | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| id     | [guides/i18n.mdx](https://github.com/withastro/starlight/blob/2a8136dd36609e778ecb182e6209e365389614b4/docs%2Fsrc%2Fcontent%2Fdocs%2Fid%2Fguides%2Fi18n.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-06 10:01 UTC, HiDeoo requested changes
Thanks for updating this translation :star2:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). I left one comment regarding some strings that should actually not be translated but otherwise, the translation looks good to me :thumbsup:

2024-10-07 03:58 UTC, iyyafi commented on docs/src/content/docs/id/guides/i18n.mdx
> +   	"expressiveCode.terminalWindowFallbackTitle": "Jendela terminal"
Ah, i miss those. thank you for the review. I will fix it soon.

2024-10-07 03:59 UTC, iyyafi commented on docs/src/content/docs/id/guides/i18n.mdx
> +   	"pagefind.searching": "Mencari [SEARCH_TERM]..."
Ok, will fix this soon too

2024-10-07 08:18 UTC, HiDeoo approved these changes
Thanks for the fixes, looks great to me now :star2:

2024-10-07 08:18 UTC, merged