i18n(de): translate components
withastro/starlight pull request #2442
Opened 2024-10-06 14:28 UTC by trueberryless

#### Description

Translation of all component sides into German language (work in progress).

Participating in Hacktoberfest!

2024-10-06 14:28 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                     | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| de     | [components/asides.mdx](https://github.com/withastro/starlight/blob/8f2b6d41d62fb0d23f1786ced570b5e1e0fee2e6/docs%2Fsrc%2Fcontent%2Fdocs%2Fde%2Fcomponents%2Fasides.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-08 14:29 UTC, delucis commented
Hi @trueberryless! You don’t need to translate all of them in one PR! This PR as it is just for the one page is fine and then you can submit additional PRs for other pages. Does that sound OK?

2024-10-08 15:15 UTC, trueberryless commented
yeah, sure, means more hacktoberfest prs, thx 😊

2024-10-08 15:47 UTC, trueberryless commented
Is Starlight / Astro moving away from Vercel to Netlify or why is the preview now on Netlify again?

2024-10-08 15:56 UTC, delucis commented
> yeah, sure, means more hacktoberfest prs, thx 😊

Yay! More PRs for everyone 🥳 

> Is Starlight / Astro moving away from Vercel to Netlify or why is the preview now on Netlify again?

We made the move back to Netlify in July for our official sites yeah. More information here: https://astro.build/blog/netlify-official-deployment-partner/

2024-10-08 16:16 UTC, delucis requested changes
Thank you for the translation @trueberryless! Mostly looks great but left a couple of small suggestions. 

The one other thing you could add is a translation for the "Preview" label shown in component previews. For that, you'd need to add a `de.json` file similar to the other ones here: https://github.com/withastro/starlight/tree/main/docs/src/content/i18n

2024-10-08 16:16 UTC, delucis commented on docs/src/content/docs/de/components/asides.mdx
> +Ein `<Aside>` kann ein optionales [`Typ`](#type) Attribute haben, welches die Farbe, das Symbol und den Standardtitel der Nebenbemerkung steuert.
I think here we should probably avoid translating "type" as it's the name of the prop that people will need to use:

```suggestion
Ein `<Aside>` kann ein optionales [`type`](#type) Attribute haben, welches die Farbe, das Symbol und den Standardtitel der Nebenbemerkung steuert.
```

2024-10-08 16:16 UTC, delucis commented on docs/src/content/docs/de/components/asides.mdx
> +Überschreibe die voreingestellten Seitentitel mit dem Attribut [`title`](#title).
I think "Seitentitel" is probably incorrect here as it doesn't control the page title but the label for the aside. Something in the direction of "Nebenbemerkung Überschrift" perhaps?

2024-10-08 16:16 UTC, delucis commented on docs/src/content/docs/de/components/asides.mdx
> +Der Titel der anzuzeigenden Nebenbemerkung.
Not sure if "Überschrift" could be more appropriate than "Titel" here too? But this correct otherwise!

2024-10-08 16:38 UTC, trueberryless commented
\lgtm

2024-10-08 20:58 UTC, delucis approved these changes
Sieht super aus — danke nochmals @trueberryless 🚀

2024-10-08 20:58 UTC, merged