i18n(de): translate using-components
withastro/starlight pull request #2455
Opened 2024-10-08 21:37 UTC by trueberryless

#### Description

Translation of `using-components.mdx` into German language.

Participating in Hacktoberfest!

2024-10-08 21:38 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                         | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| de     | [components/using-components.mdx](https://github.com/withastro/starlight/blob/011545449efa0453c38f3233f35af7abd90d33da/docs%2Fsrc%2Fcontent%2Fdocs%2Fde%2Fcomponents%2Fusing-components.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-09 13:50 UTC, trueberryless commented
Link fixed in https://github.com/withastro/starlight/pull/2458

2024-10-21 08:22 UTC, HiDeoo requested changes
Thanks for the new translation :star2:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://contribute.docs.astro.build/reviewers/reviewing-translations/). Left a few comments regarding links but except that, everything looks good to me and should be mergable once the link validation passes.

2024-10-21 08:22 UTC, HiDeoo commented on docs/src/content/docs/de/components/using-components.mdx
> +Weitere Informationen über [Verwendung von Komponenten in MDX](https://docs.astro.build/en/guides/integrations-guide/mdx/#using-components-in-mdx) findest du in der Astro-Dokumentation.
```suggestion
Weitere Informationen über [Verwendung von Komponenten in MDX](https://docs.astro.build/de/guides/integrations-guide/mdx/#using-components-in-mdx) findest du in der Astro-Dokumentation.
```

2024-10-21 08:22 UTC, HiDeoo commented on docs/src/content/docs/de/components/using-components.mdx
> +Weitere Informationen zur Verwendung von Komponenten in Markdoc-Dateien findst du in der [Astro Markdoc Integrationsdokumentation](https://docs.astro.build/de/guides/integrations-guide/markdoc/#kompo
```suggestion
Weitere Informationen zur Verwendung von Komponenten in Markdoc-Dateien findst du in der [Astro Markdoc Integrationsdokumentation](https://docs.astro.build/de/guides/integrations-guide/markdoc/#render-components).
```

Fix anchor

2024-10-21 08:22 UTC, HiDeoo commented on docs/src/content/docs/de/components/using-components.mdx
> +Verwende den Typ [`ComponentProps`](https://docs.astro.build/de/guides/typescript/#componentprops-typ) aus `astro/types`, um auf die von einer Komponente akzeptierten `Props` zu verweisen, auch wenn
```suggestion
Verwende den Typ [`ComponentProps`](https://docs.astro.build/de/guides/typescript/#componentprops-type) aus `astro/types`, um auf die von einer Komponente akzeptierten `Props` zu verweisen, auch wenn sie nicht von der Komponente selbst exportiert werden.
```

This section does not exist in the old version of the German page so let's keep the English anchor for now.

2024-10-21 14:22 UTC, trueberryless commented
Thanks for the review, should be good to go!

2024-10-22 10:35 UTC, HiDeoo approved these changes
All links are now green, thanks for the updates :raised_hands:

2024-10-22 10:35 UTC, merged