i18n(de): translate link-buttons
withastro/starlight pull request #2463
Opened 2024-10-09 15:25 UTC by trueberryless

#### Description

Translation of `link-buttons.mdx` into German language.

Participating in Hacktoberfest!

2024-10-09 15:26 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                 | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| de     | [components/link-buttons.mdx](https://github.com/withastro/starlight/blob/7deacb92e0024511a29d346df892110edbaa0c1e/docs%2Fsrc%2Fcontent%2Fdocs%2Fde%2Fcomponents%2Flink-buttons.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-09 15:27 UTC, trueberryless commented
Link fixed in https://github.com/withastro/starlight/pull/2460

2024-10-15 21:12 UTC, HiDeoo requested changes
Thanks for the new translation.

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). Left a suggestion to fix some attribute values but otherwise looks good to me :thumbsup:.

2024-10-15 21:12 UTC, HiDeoo commented on docs/src/content/docs/de/components/link-buttons.mdx
> +Optional kann das Aussehen des Link-Buttons mit dem Attribut [`variant`](#variant) angepasst werden, das auf `primär` (Standard), `sekundär` oder `minimal` gesetzt werden kann.
```suggestion
Optional kann das Aussehen des Link-Buttons mit dem Attribut [`variant`](#variant) angepasst werden, das auf `primary` (Standard), `secondary` oder `minimal` gesetzt werden kann.
```

A bit too much translation 😄

2024-10-15 21:26 UTC, HiDeoo approved these changes
> Thx for the many Hacktoberfest PRs, but I think I have more than 4 by now 😊

Amazing, thanks for participating and choosing the Starlight repo for your contributions! 🎉

2024-10-15 21:30 UTC, merged