i18n(de): translate plugins (ref)
withastro/starlight pull request #2464
Opened 2024-10-09 17:30 UTC by trueberryless

#### Description

Translation of `reference/plugins.mdx` into German language.

Participating in Hacktoberfest!

2024-10-09 17:30 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                   | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| de     | [reference/plugins.md](https://github.com/withastro/starlight/blob/1a0af68360deaf12d87502723d23fa51fa425d54/docs%2Fsrc%2Fcontent%2Fdocs%2Fde%2Freference%2Fplugins.md) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-20 09:39 UTC, trueberryless commented
Links fixed in #2476 and #2459

2024-10-21 08:57 UTC, HiDeoo requested changes
Thanks for another translation :thumbsup:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://contribute.docs.astro.build/reviewers/reviewing-translations/). Left a few tiny comments regarding some comments that could be translated, but otherwise, the translation looks good to me and should be mergeable once link validation passes.

2024-10-21 08:57 UTC, HiDeoo commented on docs/src/content/docs/de/reference/plugins.md
> +  label: Plugins
Related discussion for reference [withastro/starlight/pull/2470/files/2b486d1b1fa4acf3f0c87da750f3ce219794f78e#diff-9185fd84aba7e9a14b394be96e2bd3562baac10c0285be708a3109c5cbe72802](https://github.com/withastro/starlight/pull/2470/files/2b486d1b1fa4acf3f0c87da750f3ce219794f78e#diff-9185fd84aba7e9a14b394be96e2bd3562baac10c0285be708a3109c5cbe72802)

2024-10-21 08:57 UTC, HiDeoo commented on docs/src/content/docs/de/reference/plugins.md
> +      // Only add the React integration if it's not already loaded.
We could translate this comment.

2024-10-21 08:57 UTC, HiDeoo commented on docs/src/content/docs/de/reference/plugins.md
> +      // Some long process…
Same here and also potentially the log itself if you want.

2024-10-21 08:57 UTC, HiDeoo commented on docs/src/content/docs/de/reference/plugins.md
> +[long-process-plugin] Starting long process…
If you decide to translate the log too, this one should be updated.

2024-10-21 13:46 UTC, trueberryless commented on docs/src/content/docs/de/reference/plugins.md
> +      // Only add the React integration if it's not already loaded.
We should indeed 😂

2024-10-21 13:50 UTC, trueberryless commented
"Left comments regarding comments"

If this ain't a tagline, I don't know what is!

2024-10-22 08:07 UTC, HiDeoo reviewed
Should fix the `guides/i18n` related link issues

2024-10-22 08:07 UTC, HiDeoo commented on docs/src/content/docs/de/reference/plugins.md
> +Eine Callback-Funktion zum Hinzufügen oder Aktualisieren von Übersetzungsstrings, die in Starlights [Lokalisierungs-APIs](/de/guides/i18n/#ui-%C3%BCbersetzungen-verwenden) verwendet werden.
```suggestion
Eine Callback-Funktion zum Hinzufügen oder Aktualisieren von Übersetzungsstrings, die in Starlights [Lokalisierungs-APIs](/de/guides/i18n/#ui-übersetzungen-verwenden) verwendet werden.
```

2024-10-22 08:07 UTC, HiDeoo commented on docs/src/content/docs/de/reference/plugins.md
> +Um die eingefügten Übersetzungen in der Benutzeroberfläche deines Plugins zu verwenden, folge der Anleitung [„UI-Übersetzungen verwenden“](/de/guides/i18n/#ui-%C3%BCbersetzungen-verwenden).
```suggestion
Um die eingefügten Übersetzungen in der Benutzeroberfläche deines Plugins zu verwenden, folge der Anleitung [„UI-Übersetzungen verwenden“](/de/guides/i18n/#ui-übersetzungen-verwenden).
```

2024-10-22 09:54 UTC, HiDeoo approved these changes
And we're back on track, all links are now validated. Thanks a lot for updating the PR, ready to be merged now :star2:

2024-10-22 09:54 UTC, merged