i18n(id): Update reference/frontmatter.md translation
withastro/starlight pull request #2468
Opened 2024-10-11 14:23 UTC by iyyafi

#### Description
- Update ID translation for reference/frontmatter.md file

##### PS: I am participating in Hacktoberfest. Please add hacktoberfest-accepted label in this PR. Thank you

2024-10-11 14:23 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                           | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| id     | [reference/frontmatter.md](https://github.com/withastro/starlight/blob/9493282019526cb55056eaecdb03b70d1f4e4fd9/docs%2Fsrc%2Fcontent%2Fdocs%2Fid%2Freference%2Ffrontmatter.md) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-14 21:06 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view). Left a suggestion that should fix the link issue but otherwise looks good to me :thumbsup:

2024-10-15 23:54 UTC, iyyafi commented on docs/src/content/docs/id/reference/frontmatter.md
> +**tipe:** Skema Zod atau fungsi yang mengembalikan skema Zod
Ah i see, i will commit this suggestion. thank you.

2024-10-15 23:55 UTC, iyyafi commented on docs/src/content/docs/id/reference/frontmatter.md
> +Tetapkan apakah halaman ini harus dianggap sebagai draf dan tidak disertakan dalam [versi produksi](https://docs.astro.build/en/reference/cli-reference/#astro-build) dan [grup tautan yang dibuat seca
Thank you, i also commit this suggestion

2024-10-16 05:44 UTC, HiDeoo approved these changes
Thanks for updating the PR, looks perfect to me now :rocket:

2024-10-16 05:47 UTC, merged