i18n(de): translate pages
withastro/starlight pull request #2469
Opened 2024-10-11 14:49 UTC by trueberryless

#### Description

Translation of `pages.mdx` into German language.

Participating in Hacktoberfest!

2024-10-11 14:50 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                           | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| de     | [guides/pages.mdx](https://github.com/withastro/starlight/blob/4127422f0cc1930951e4f2a3174dad0a14c45877/docs%2Fsrc%2Fcontent%2Fdocs%2Fde%2Fguides%2Fpages.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-20 09:43 UTC, trueberryless commented
Links fixed in #2458, #2470 and #2480

2024-10-21 09:08 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://contribute.docs.astro.build/reviewers/reviewing-translations/). Left a few comments/suggestions but overall it looks good to me and should be mergeable once links validation passes.

2024-10-21 09:08 UTC, HiDeoo commented on docs/src/content/docs/de/guides/pages.mdx
> +##### `Sidebar`
```suggestion
##### `sidebar`
```

This is a property name so should not be capitalized.

2024-10-21 09:08 UTC, HiDeoo commented on docs/src/content/docs/de/guides/pages.mdx
> +				{ label: 'Ursa Minor', link: '/ursa-minor/', Abzeichen: 'Stub' },
```suggestion
				{ label: 'Ursa Minor', link: '/ursa-minor/', badge: 'Platzhalter' },
```

The property name should not be translated and I think we used "Platzhalter" in https://starlight.astro.build/de/guides/sidebar/#abzeichenvarianten

2024-10-21 13:43 UTC, trueberryless commented
Thanks for the review, should be good to go!

2024-10-22 10:45 UTC, HiDeoo approved these changes
Thanks for the updates, we should be good to go now on this one too :star2:

2024-10-22 10:45 UTC, merged