i18n(de): update translation i18n
withastro/starlight pull request #2476
Opened 2024-10-14 17:37 UTC by trueberryless

#### Description

Translation of `i18n.mdx` into German language.

Participating in Hacktoberfest!

2024-10-14 17:38 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                         | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| de     | [guides/i18n.mdx](https://github.com/withastro/starlight/blob/61868e2f985f99d97d8aa6a3703fd6092d31e8e0/docs%2Fsrc%2Fcontent%2Fdocs%2Fde%2Fguides%2Fi18n.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-20 09:35 UTC, trueberryless commented
Links fixed in #2476 and #2459

2024-10-21 07:33 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://contribute.docs.astro.build/reviewers/reviewing-translations/). I left a few suggestions and questions but other than that, the translation looks good to me.

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +Für fortgeschrittene i18n-Szenarien unterstützt Starlight auch die Konfiguration der Internationalisierung mit der Option [Astro's `i18n` config](https://docs.astro.build/de/guides/internationalizati
Just to double check, is "Astro's `i18n` config" expected or something that could have been missed? Asking as it's identical to the English version.

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +Für fortgeschrittene i18n-Szenarien unterstützt Starlight auch die Konfiguration der Internationalisierung mit der Option [Astro's `i18n` config](https://docs.astro.build/de/guides/internationalizati
```suggestion
Für fortgeschrittene i18n-Szenarien unterstützt Starlight auch die Konfiguration der Internationalisierung mit der Option [Astro's `i18n` config](https://docs.astro.build/de/guides/internationalization/#configure-i18n-routing).
```

Invalid anchor

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +Mehr über Inhaltssammlungsschemata erfährst du in [„Defining a collection schema“](https://docs.astro.build/de/guides/content-collections/#definieren-eines-sammelschemas) in den Astro-Dokumenten.
I assume the "Defining a collection schema" link name was forgotten.

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +Mehr über Inhaltssammlungsschemata erfährst du in [„Defining a collection schema“](https://docs.astro.build/de/guides/content-collections/#definieren-eines-sammelschemas) in den Astro-Dokumenten.
```suggestion
Mehr über Inhaltssammlungsschemata erfährst du in [„Defining a collection schema“](https://docs.astro.build/de/guides/content-collections/#defining-a-collection-schema) in den Astro-Dokumenten.
```

Invalid anchor

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +Du kannst die API auch bei [Endpunkten](https://docs.astro.build/de/guides/endpoints/) verwenden, wo das Objekt `locals` als Teil des [Endpunkt-Kontextes] (https://docs.astro.build/de/reference/api-r
```suggestion
Du kannst die API auch bei [Endpunkten](https://docs.astro.build/de/guides/endpoints/) verwenden, wo das Objekt `locals` als Teil des [Endpunkt-Kontextes](https://docs.astro.build/de/reference/api-reference/#contextlocals) verfügbar ist:
```

Invalid link markup (extra space).

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +<!-- Renders: <a href="...">Astro Dokumentation</a> -->
Is "Renders" expected here or missed from the original translation?

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +<!-- Renders: <a href="...">Astro-Dokumentation für Astro DB</a> -->
Same here for "Renders"

2024-10-21 07:33 UTC, HiDeoo commented on docs/src/content/docs/de/guides/i18n.mdx
> +Du kannst auf Starlights [eingebaute UI-Strings](/de/guides/i18n/#starlights-ui-%C3%BCbersetzen) sowie auf [benutzerdefinierte](/de/guides/i18n/#%C3%BCbersetzungsschema-erweitern) und [plugin-provide
```suggestion
Du kannst auf Starlights [eingebaute UI-Strings](/de/guides/i18n/#starlights-ui-übersetzen) sowie auf [benutzerdefinierte](/de/guides/i18n/#übersetzungsschema-erweitern) und [plugin-provided](/de/reference/plugins/#injecttranslations) UI-Strings über eine einheitliche API zugreifen, die von [i18next](https://www.i18next.com/) unterstützt wird.
```

This should fix the same-page link errors.

2024-10-21 13:41 UTC, trueberryless commented
Thanks for your review, sry that I missed that many translations...

2024-10-22 07:57 UTC, HiDeoo approved these changes
Thanks for updating the PR, should be good to go :rocket:

2024-10-22 07:57 UTC, merged