i18n(pt-PT): update outdated pages
withastro/starlight pull request #2741
Opened 2024-12-26 11:16 UTC by rgilsimoes

#### Description

- Updated following pages:
pt-pt/resources/community-content.mdx
pt-pt/resources/plugins.mdx
pt-pt/environmental-impact.md
pt-pt/index.mdx
pt-pt/manual-setup.mdx

2024-12-26 11:16 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                            | Note                                               |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| pt-pt  | [environmental-impact.md](https://github.com/withastro/starlight/blob/821ecc41225f1f7fe4110a0057f8a7ee6644333d/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fenvironmental-impact.md)                   | Localization changed, will be marked as complete.  |
| pt-pt  | [index.mdx](https://github.com/withastro/starlight/blob/821ecc41225f1f7fe4110a0057f8a7ee6644333d/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Findex.mdx)                                               | Localization changed, will be marked as complete.  |
| pt-pt  | [manual-setup.mdx](https://github.com/withastro/starlight/blob/821ecc41225f1f7fe4110a0057f8a7ee6644333d/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fmanual-setup.mdx)                                 | Localization changed, will be marked as complete.  |
| pt-pt  | [resources/community-content.mdx](https://github.com/withastro/starlight/blob/821ecc41225f1f7fe4110a0057f8a7ee6644333d/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fresources%2Fcommunity-content.mdx) | Localization changed, will be marked as complete.  |
| pt-pt  | [resources/plugins.mdx](https://github.com/withastro/starlight/blob/821ecc41225f1f7fe4110a0057f8a7ee6644333d/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fresources%2Fplugins.mdx)                     | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2025-01-03 08:49 UTC, HiDeoo requested changes
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://contribute.docs.astro.build/reviewers/reviewing-translations/). I left a suggestion to fix the link issue and a few comments but other than that, the translation looks good to me.

2025-01-03 08:49 UTC, HiDeoo commented on docs/src/content/docs/pt-pt/manual-setup.mdx
> +Para desabilitar a pré-renderização das suas páginas Starlight coloque a [opção de config `prerender`](/reference/configuration/#prerender) a `false`.
```suggestion
Para desabilitar a pré-renderização das suas páginas Starlight coloque a [opção de config `prerender`](/pt-pt/reference/configuration/#prerender) a `false`.
```

2025-01-03 08:49 UTC, HiDeoo commented on docs/src/content/docs/pt-pt/manual-setup.mdx
It looks like this file is missing the changes from https://github.com/withastro/starlight/pull/2612/files#diff-fcb19e4d7abeabedf0cf00b59329f63544028e76aee0868ed9335ef9fd2f55a6

Would you be ok to update this file with them?

2025-01-03 08:49 UTC, HiDeoo commented on docs/src/content/docs/pt-pt/resources/plugins.mdx
> +		description="Tema de `Pastel Suavizante` para o Starlight"
Just to double check, is the backticks around "Pastel Suavizante" expected?

2025-01-07 19:46 UTC, rgilsimoes commented on docs/src/content/docs/pt-pt/resources/plugins.mdx
> +		description="Tema de `Pastel Suavizante` para o Starlight"
Yes, because it's the name of the Theme.

2025-01-07 22:49 UTC, delucis commented on docs/src/content/docs/pt-pt/resources/plugins.mdx
> +		description="Tema de `Pastel Suavizante` para o Starlight"
Ah I think that might be a misunderstanding. The name of the theme is “catppuccin”. The English reads:

> Soothing pastel theme for Starlight

Which means more like “A theme for Starlight in soothing pastel colors”

So something like “Tema pastel suave para Starlight” or “Tema suave em tons pastel para Starlight” might be a closer match.

2025-01-08 17:50 UTC, merged