feat: add support for light / dark hero images
withastro/starlight pull request #280
Opened 2023-06-30 10:45 UTC by cbontems

#### What kind of changes does this PR include?

- Changes to Starlight code

#### Description

- Modifies the hero image schema to add 2 optional images properties : dark and light.
- Modifies the Hero component to display an hero image with the following logic:
	- if a file property is set, use it for all modes
	- if dark and light properties are set, use them accordingly
	- if neither file nor dark are set, and html is set, use raw html
	- otherwise, display nothing
- Modifies the frontmatter.md reference to reflect the changes.

> ***note***
> I have been considering allowing for darkHtml and lightHtml in the same way, but finally thought it might be too much for most users. And I guess people using raw html know how to handle this. What to you think ?

2023-09-09 07:49 UTC, lorenzolewis requested changes
Since there's been quite a few changes to the codebase this PR has a few conflicts. I'm not sure of the best way to communicate those so I've created a diff that I'll include below. With that diff applied and then the suggestion on updating the docs phrasing this one looks good to me 🥳 

```diff
diff --git a/packages/starlight/components/Hero.astro b/packages/starlight/components/Hero.astro
index 1fccc61..fbf56b8 100644
--- a/packages/starlight/components/Hero.astro
+++ b/packages/starlight/components/Hero.astro
@@ -4,160 +4,146 @@ import { Image } from 'astro:assets';
 import CallToAction from './CallToAction.astro';
 
 interface Props {
-  fallbackTitle: string;
-  hero: NonNullable<CollectionEntry<'docs'>['data']['hero']>;
+	fallbackTitle: string;
+	hero: NonNullable<CollectionEntry<'docs'>['data']['hero']>;
 }
 
-const {
-  title = Astro.props.fallbackTitle,
-  tagline,
-  image,
-  actions,
-} = Astro.props.hero;
+const { title = Astro.props.fallbackTitle, tagline, image, actions } = Astro.props.hero;
 
 const imageAttrs = {
-  loading: 'eager' as const,
-  decoding: 'async' as const,
-  width: 400,
-  height: 400,
-  alt: image?.alt,
+	loading: 'eager' as const,
+	decoding: 'async' as const,
+	width: 400,
+	height: 400,
+	alt: image?.alt,
 };
 // darkImage is the default and uses either file, dark or raw html
 const darkImage = image?.file ? image.file : image?.dark ? image.dark : null;
 // lightImage is only used if darkImage is also used
-const lightImage = image?.file ? null : (image?.dark && image?.light) ? image.light : null;
+const lightImage = image?.file ? null : image?.dark && image?.light ? image.light : null;
 // rawHtml is only used if darkImage is not used
 const rawHtml = !darkImage && image?.html ? image.html : null;
 ---
 
 <div class="hero">
-
-  {
-    darkImage && (
-    darkImage.format === 'svg' ? (
-        <img src={darkImage.src} {...imageAttrs} class:list={{ 'dark-only': Boolean(lightImage) }}/>
-      ) : (
-        <Image src={darkImage} {...imageAttrs} class:list={{ 'dark-only': Boolean(lightImage) }}/>
-      )
-    ) 
-  }
-  {
-    lightImage && (
-    lightImage.format === 'svg' ? (
-        <img src={lightImage.src} {...imageAttrs} class="light-only"/>
-      ) : (
-        <Image src={lightImage} {...imageAttrs} class="light-only"/>
-      )
-    ) 
-  }
-{
-  rawHtml && <div class="hero-html flex" set:html={rawHtml} />
-}
-  <div class="flex stack">
-    <div class="flex copy">
-      <h1 id="_top" data-page-title set:html={title} />
-      {tagline && <div class="tagline" set:html={tagline} />}
-    </div>
-    {
-      actions.length > 0 && (
-        <div class="flex actions">
-          {actions.map(({ text, ...attrs }) => (
-            <CallToAction {...attrs} set:html={text} />
-          ))}
-        </div>
-      )
-    }
-  </div>
+	{
+		darkImage &&
+			(darkImage.format === 'svg' ? (
+				<img
+					src={darkImage.src}
+					{...imageAttrs}
+					class:list={{ 'dark-only': Boolean(lightImage) }}
+				/>
+			) : (
+				<Image src={darkImage} {...imageAttrs} class:list={{ 'dark-only': Boolean(lightImage) }} />
+			))
+	}
+	{
+		lightImage &&
+			(lightImage.format === 'svg' ? (
+				<img src={lightImage.src} {...imageAttrs} class="light-only" />
+			) : (
+				<Image src={lightImage} {...imageAttrs} class="light-only" />
+			))
+	}
+	{rawHtml && <div class="hero-html sl-flex" set:html={rawHtml} />}
+	<div class="sl-flex stack">
+		<div class="sl-flex copy">
+			<h1 id="_top" data-page-title set:html={title} />
+			{tagline && <div class="tagline" set:html={tagline} />}
+		</div>
+		{
+			actions.length > 0 && (
+				<div class="sl-flex actions">
+					{actions.map(({ text, ...attrs }) => (
+						<CallToAction {...attrs} set:html={text} />
+					))}
+				</div>
+			)
+		}
+	</div>
 </div>
 
 <style>
-  .hero {
-    display: grid;
-    align-items: center;
-    gap: 1rem;
-    padding-bottom: 1rem;
-  }
-
-  .hero > img,
-  .hero > .hero-html {
-    object-fit: contain;
-    width: min(70%, 20rem);
-    height: auto;
-    margin-inline: auto;
-  }
-
-  :global([data-theme='light']) .dark-only {
-    display: none;
-  }
-  :global([data-theme='dark']) .light-only {
-    display: none;
-  }
-
-  .stack {
-    flex-direction: column;
-    gap: clamp(1.5rem, calc(1.5rem + 1vw), 2rem);
-    text-align: center;
-  }
-
-  .copy {
-    flex-direction: column;
-    gap: 1rem;
-    align-items: center;
-  }
-
-  .copy > * {
-    max-width: 50ch;
-  }
-
-  h1 {
-    font-size: clamp(
-      var(--sl-text-3xl),
-      calc(0.25rem + 5vw),
-      var(--sl-text-6xl)
-    );
-    line-height: var(--sl-line-height-headings);
-    font-weight: 600;
-    color: var(--sl-color-white);
-  }
-
-  .tagline {
-    font-size: clamp(
-      var(--sl-text-base),
-      calc(0.0625rem + 2vw),
-      var(--sl-text-xl)
-    );
-    color: var(--sl-color-gray-2);
-  }
-
-  .actions {
-    gap: 1rem 2rem;
-    flex-wrap: wrap;
-    justify-content: center;
-  }
-
-  @media (min-width: 50rem) {
-    .hero {
-      grid-template-columns: 7fr 4fr;
-      gap: 3%;
-      padding-block: clamp(2.5rem, calc(1rem + 10vmin), 10rem);
-    }
-
-    .hero > img,
-    .hero > .hero-html {
-      order: 2;
-      width: min(100%, 25rem);
-    }
-
-    .stack {
-      text-align: start;
-    }
-
-    .copy {
-      align-items: flex-start;
-    }
-
-    .actions {
-      justify-content: flex-start;
-    }
-  }
+	.hero {
+		display: grid;
+		align-items: center;
+		gap: 1rem;
+		padding-bottom: 1rem;
+	}
+
+	.hero > img,
+	.hero > .hero-html {
+		object-fit: contain;
+		width: min(70%, 20rem);
+		height: auto;
+		margin-inline: auto;
+	}
+
+	:global([data-theme='light']) .dark-only {
+		display: none;
+	}
+	:global([data-theme='dark']) .light-only {
+		display: none;
+	}
+
+	.stack {
+		flex-direction: column;
+		gap: clamp(1.5rem, calc(1.5rem + 1vw), 2rem);
+		text-align: center;
+	}
+
+	.copy {
+		flex-direction: column;
+		gap: 1rem;
+		align-items: center;
+	}
+
+	.copy > * {
+		max-width: 50ch;
+	}
+
+	h1 {
+		font-size: clamp(var(--sl-text-3xl), calc(0.25rem + 5vw), var(--sl-text-6xl));
+		line-height: var(--sl-line-height-headings);
+		font-weight: 600;
+		color: var(--sl-color-white);
+	}
+
+	.tagline {
+		font-size: clamp(var(--sl-text-base), calc(0.0625rem + 2vw), var(--sl-text-xl));
+		color: var(--sl-color-gray-2);
+	}
+
+	.actions {
+		gap: 1rem 2rem;
+		flex-wrap: wrap;
+		justify-content: center;
+	}
+
+	@media (min-width: 50rem) {
+		.hero {
+			grid-template-columns: 7fr 4fr;
+			gap: 3%;
+			padding-block: clamp(2.5rem, calc(1rem + 10vmin), 10rem);
+		}
+
+		.hero > img,
+		.hero > .hero-html {
+			order: 2;
+			width: min(100%, 25rem);
+		}
+
+		.stack {
+			text-align: start;
+		}
+
+		.copy {
+			align-items: flex-start;
+		}
+
+		.actions {
+			justify-content: flex-start;
+		}
+	}
 </style>
diff --git a/packages/starlight/schema.ts b/packages/starlight/schema.ts
index 320b30b..5345c46 100644
--- a/packages/starlight/schema.ts
+++ b/packages/starlight/schema.ts
@@ -1,121 +1,177 @@
-import { z } from "astro/zod";
-import { HeadConfigSchema } from "./schemas/head";
-import { TableOfContentsSchema } from "./schemas/tableOfContents";
-import { Icons } from "./components/Icons";
-export { i18nSchema } from "./schemas/i18n";
+import { z } from 'astro/zod';
+import { HeadConfigSchema } from './schemas/head';
+import { PrevNextLinkConfigSchema } from './schemas/prevNextLink';
+import { TableOfContentsSchema } from './schemas/tableOfContents';
+import { Icons } from './components/Icons';
+import { BadgeConfigSchema } from './schemas/badge';
+export { i18nSchema } from './schemas/i18n';
 
 type IconName = keyof typeof Icons;
 const iconNames = Object.keys(Icons) as [IconName, ...IconName[]];
 
 type ImageFunction = () => z.ZodObject<{
-  src: z.ZodString;
-  width: z.ZodNumber;
-  height: z.ZodNumber;
-  format: z.ZodUnion<
-    [
-      z.ZodLiteral<"png">,
-      z.ZodLiteral<"jpg">,
-      z.ZodLiteral<"jpeg">,
-      z.ZodLitera [...]

2023-09-09 07:49 UTC, lorenzolewis commented on docs/src/content/docs/reference/frontmatter.md
> +To add support for a dark / light responsive hero image, modify the `hero.image` object like this, leaving other properties untouched.
```suggestion
You can display different versions of the hero image in light and dark modes.
```

Following similar phrasing as https://starlight.astro.build/guides/customization/#light-and-dark-logo-variants

2023-09-09 07:50 UTC, lorenzolewis commented
Oh, and one last thing I forgot is to mention generating a changeset for this one.

2023-09-29 08:21 UTC, alvaro17f approved these changes

2023-10-26 16:58 UTC, delucis commented
Took a pass at getting this cleaned up so we can finally ship it! Quick summary of the changes I made:

- Made the light/dark styles into global CSS utilities so we can share them between the site title and the hero
- Made the `hero.image` config a union of three types instead of lots of optional types. Valid config is now `{ file; alt? }` or `{ light; dark; alt? }` or `{ html }`. I also updated the reference docs to reflect that.

Thanks again for everyone’s patience on this one!

2023-10-26 18:53 UTC, HiDeoo approved these changes
Amazing update to make it to the finish line. :clap: 

The code is very clean, I love the stricter schema. Also tested locally and it works great. 

I guess we could potentially have a component to render either `<Image/>` or `<img/>` to avoid some repetition, but it happens only 2 times in a single component so it may be better to keep it as is.

This looks good to me 🚀 (altho I almost feel a bit bad with the new `alt` documentation that we do not use it in our index page :sweat_smile:)

Great work everyone.

2023-10-26 21:51 UTC, delucis commented
> I almost feel a bit bad with the new `alt` documentation that we do not use it in our index page 😅

`alt` defaults to `""`, hiding the image from assistive tech, so I think that’s OK for our hero section where the star is decorative, but yeah definitely wouldn’t be if someone’s hero image contained come more informative content.

2023-10-26 22:01 UTC, HiDeoo commented
> Oh, actually, I should double check. I think `<Image />` now allows passing an SVG? We might be able to clean that up in a follow-up PR assuming it was in 3.2 or below.
> 
> **Edit:** Will run a test, but the change I was thinking of released in 2.8.3, so would definitely be in scope: [withastro/astro#7643](https://github.com/withastro/astro/pull/7643)

Oh, totally missed that one, would be great indeed.

2023-10-26 22:01 UTC, delucis commented
**Update:** Yup! `<Image />` is fine with SVGs now, so that’s a really nice thing to clean up 🎉

2023-10-30 18:15 UTC, lorenzolewis commented
The only minor feedback I have is that `LogoConfig` uses `src` instead of `file` that is used for this, so that's slightly inconsistent. Other than that it lgtm!

2023-10-31 12:45 UTC, delucis commented
> The only minor feedback I have is that `LogoConfig` uses `src` instead of `file` that is used for this, so that's slightly inconsistent. Other than that it lgtm!

Yes, that’s true (also the case with the current hero image support). It was chosen to distinguish `file` from `html`, although maybe both logo and hero should in fact support the same here. Maybe worth a follow-up discussion? Don’t mind us revisiting that API naming and making a breaking change later if it makes sense.

2023-11-01 22:16 UTC, merged