i18n(pt-BR): Translate `manual-setup.mdx` & `showcase.md`
withastro/starlight pull request #491
Opened 2023-08-10 21:49 UTC by Yan-Thomas

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

Translation for both `manual-setup.mdx` and `showcase.md` files.

2023-08-10 21:50 UTC, astrobot-houston commented
## size-limit report 📦 
| Path          | Size          |
| ------------- | ------------- |
| /index.html   | 9.57 KB (0%)  |
| /_astro/*.js  | 16.33 KB (0%) |
| /_astro/*.css | 8.39 KB (0%)  |

2023-08-10 22:27 UTC, delucis approved these changes
LGTM @Yan-Thomas — thank you!

2023-08-11 01:23 UTC, Alynva requested changes
Just a little fix. Otherwise, LGTM! 😄

2023-08-11 01:23 UTC, Alynva commented on docs/src/content/docs/pt-br/manual-setup.mdx
> +Ele vai instalar as as dependências necessárias e adicionar o Starlight no array `integrations` do seu arquivo de configuração do Astro.
Duas vezes "as"
```suggestion
Ele vai instalar as dependências necessárias e adicionar o Starlight no array `integrations` do seu arquivo de configuração do Astro.
```

2023-08-11 14:30 UTC, merged