Fix translation status page
withastro/starlight pull request #495
Opened 2023-08-11 02:33 UTC by Waxer59

#### What kind of changes does this PR include?

- Changes to Starlight code

## Before: 
![image](https://github.com/withastro/starlight/assets/78129249/c886da80-900b-458f-8a4b-5846bea46cc4)

## After:
![image](https://github.com/withastro/starlight/assets/78129249/1b447f8c-0baa-4222-931d-86417ecc5753)

#### Description

- What does this PR change? Give us a brief description.

The page tracking error has been resolved. This error occurs when there is a case sensitivity issue in the `pt-br` translations folder and a change in capitalization in the language string, as can be seen in the Astro configuration file under the `locales` variable:

```js
export const locales = {
    root: { label: 'English', lang: 'en' },
    de: { label: 'Deutsch', lang: 'de' },
    es: { label: 'Español', lang: 'es' },
    ja: { label: '日本語', lang: 'ja' },
    fr: { label: 'Français', lang: 'fr' },
    it: { label: 'Italiano', lang: 'it' },
    zh: { label: '简体中文', lang: 'zh' },
    'pt-br': { label: 'Português do Brasil', lang: 'pt-BR' },
};
```

Another solution could be to change the `locales['pt-br'][lang]` field to `pt-BR`, or rename the `pt-br` folder to `pt-BR`. These would also be simpler and valid solutions to this issue. However, in this solution, I haven't made any changes to other files in case it's preferred to keep them that way or to avoid causing any problems in other files.

2023-08-11 02:33 UTC, Waxer59 commented on docs-i18n-tracker/lib/translation-status/builder.ts
> +
```suggestion
```

2023-08-11 17:42 UTC, dreyfus92 requested changes
This will sort alphabetically locales.

2023-08-11 17:42 UTC, dreyfus92 commented on docs-i18n-tracker/build.ts
> +		.reduce((acc, { lang }) => lang !== "en" ? [lang, ...acc] : acc, []),
```suggestion
		.reduce((acc, { lang }) => lang !== "en" ? [lang, ...acc] : acc, []).sort(),
```

2023-08-11 17:45 UTC, Waxer59 commented
Done!, thanks for the review 🤠

2023-08-12 19:35 UTC, delucis approved these changes
Thanks for the fix @Waxer59!

2023-08-12 19:36 UTC, merged