i18n(pt-BR): Translate `404.md` & `authoring-content.md`
withastro/starlight pull request #504
Opened 2023-08-13 18:17 UTC by Yan-Thomas

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

Translation for `404.md` & `authoring-content.md`

2023-08-13 18:18 UTC, astrobot-houston commented
## size-limit report 📦 
| Path          | Size          |
| ------------- | ------------- |
| /index.html   | 9.57 KB (0%)  |
| /_astro/*.js  | 16.33 KB (0%) |
| /_astro/*.css | 8.39 KB (0%)  |

2023-08-13 19:02 UTC, Alynva requested changes

2023-08-21 11:05 UTC, delucis reviewed
Noticed one small change needed here, but otherwise LGTM!

2023-08-21 11:05 UTC, delucis commented on docs/src/content/docs/pt-br/404.md
> +      link: /
This link should point to the Portuguese home page:

```suggestion
      link: /pt-br/
```

2023-08-21 11:39 UTC, merged