i18n(pt-BR): Translate `i18n.mdx`
withastro/starlight pull request #505
Opened 2023-08-13 18:53 UTC by Yan-Thomas

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

PT-BR translation for `i18n.mdx`

2023-08-13 18:54 UTC, astrobot-houston commented
## size-limit report 📦 
| Path          | Size          |
| ------------- | ------------- |
| /index.html   | 9.57 KB (0%)  |
| /_astro/*.js  | 16.33 KB (0%) |
| /_astro/*.css | 8.39 KB (0%)  |

2023-08-13 19:23 UTC, Alynva requested changes

2023-08-13 19:23 UTC, Alynva commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +description: Aprenda como configurar seu site Starlight para suportar várias linguagens.
Acredito que uma melhor tradução de "languages" seja "idiomas", fica a seu critério se talvez atualiza em toda a página.

```suggestion
description: Aprenda como configurar seu site Starlight para suportar vários idiomas.
```

2023-08-13 19:23 UTC, Alynva commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +   				pt: {
Nossa documentação utiliza [`pt-br`](https://github.com/withastro/starlight/blob/main/docs/astro.config.mjs#L12) mas estamos sugerindo usarem `pt`?

2023-08-13 19:23 UTC, Alynva commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +Você pode usar um local raiz” para servir uma linguagem language sem nenhum prefixo de i18n no seu caminho. Por exemplo, se Português é seu local raiz, um caminho de página em Português se pareceria
Faltou uma aspas aqui, e sobrou uma palavra em inglês. Eu pessoalmente prefiro a aspas duplas normal, ainda não entendi o motivo de usarem essas.

E acredito que o "locale" aqui não está com o mesmo significado da tradução. No original ele remete à configuração da integração, onde se usa `defaultLocale` e `locales` para se referir aos idiomas e localizações (no sentido de internacionalização). Talvez "é seu idioma raiz" fique adequado, mas deixo aberto para discussão.

```suggestion
Você pode usar um local “raiz” para servir uma linguagem sem nenhum prefixo de i18n no seu caminho. Por exemplo, se Português é seu local raiz, um caminho de página em Português se pareceria com `/sobre` ao invés de `/pt/sobre`.
```

2023-08-13 19:23 UTC, Alynva commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +Starlight espera que você crie páginas equivalentes em todas as suas linguagens. Por exemplo, se você tem um arquivo `en/about.md` crie, um `about.md` para cada outra linguagem que você suporta. Isso
Pequena correção.

```suggestion
Starlight espera que você crie páginas equivalentes em todas as suas linguagens. Por exemplo, se você tem um arquivo `en/about.md` crie, um `about.md` para cada outra linguagem que você suporta. Isso permite que Starlight providencie conteúdo de fallback automático para páginas que você ainda não tenha traduzidas.
```

2023-08-13 19:23 UTC, Alynva commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +Se uma tradução ainda não está disponível para uma linguagem, Starlight irá mostrar aos leitores o conteúdo dessa página na linguagem padrão (definida através de `defaultLocale`). Por exemplo, se voc
```suggestion
Se uma tradução ainda não está disponível para uma linguagem, Starlight irá mostrar aos leitores o conteúdo dessa página na linguagem padrão (definida através de `defaultLocale`). Por exemplo, se você ainda não criou uma versão em Francês da sua página "Sobre" e sua linguagem padrão é Inglês, visitantes de `/fr/about` irão ver o conteúdo em Inglês de `/en/about` com um aviso de que esta página ainda não foi traduzida. Isso te ajuda a adicionar conteúdo na sua linguagem padrão e então progressivamente traduzí-la quando seus tradutores tiverem tempo.
```

2023-08-13 23:15 UTC, Yan-Thomas commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +description: Aprenda como configurar seu site Starlight para suportar várias linguagens.
Acredito que nesse caso deveríamos usar "língua" então, idioma é apenas quando há um Estado Político organizado por trás, o que entra mais na questão política, e nada impede alguém de fazer uma documentação em Klingon... ou algo do gênero 😅

2023-08-13 23:20 UTC, Yan-Thomas commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +   				pt: {
No original o exemplo usa Inglês, eu mudei para Português mas pelo charme da proximidade, caso eu colocasse `pt-br` teria que utilizar aspas na configuração e o `lang: 'pt-BR'` para deixar o exemplo correto, então quis simplificar. Acredito que isso não estejamos realmente "recomendando" com isso.

2023-08-21 13:04 UTC, delucis commented on docs/src/content/docs/pt-br/guides/i18n.mdx
> +Strings da UI são providenciadas para Inglês, Tcheco, Francês, Alemão, Italiano, Japonês, Português, Holandês, Dinarmaquês, Espanhol, Turco, Árabe, Norueguês e Chinês Simplificado por padrão, e nós a
Heads up that we’ve added Farsi, Korean, and Swedish to this list since this was translated. Sorry not to get to this sooner!

2023-08-21 16:48 UTC, Yan-Thomas commented
This should be good to go! Fully PT-BR Starlight Docs, here we go 🚀

2023-08-21 16:48 UTC, merged