i18n(ja): Add sidebar.mdx
withastro/starlight pull request #697
Opened 2023-09-10 04:08 UTC by morinokami

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- Add sidebar.mdx.
  - The diffs in https://github.com/withastro/starlight/pull/696 are already included (so this PR should be merged after that PR has been merged).

2023-09-28 15:40 UTC, trueberryless requested changes
Thank you, @morinokami! I'm not 100% sure how links in examples should be handled. However, I looked at the italian translation and found that all examples link to englisch content. Therefore, I _think_ you need to make these little improvements on every sidebar example.

As I said, I'm not sure if I'm correct. Please inform me if you know more than me...

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +		{ label: 'CSSとスタイリング', link: '/ja/guides/css-and-tailwind/' },
I'm not 100% sure how links in examples should be handled. However, I looked at the italian translation and found that all examples link to englisch content. Therefore, I _think_ you need to make this little improvement on every sidebar example:

```suggestion
		{ label: 'CSSとスタイリング', link: '/guides/css-and-tailwind/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +		{ label: 'CSSとスタイリング', link: '/ja/guides/css-and-tailwind/' },
```suggestion
		{ label: 'CSSとスタイリング', link: '/guides/css-and-tailwind/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +				{ label: 'コンポーネント', link: '/ja/guides/components/' },
```suggestion
				{ label: 'コンポーネント', link: '/guides/components/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +				{ label: '国際化（i18n）', link: '/ja/guides/i18n/' },
```suggestion
				{ label: '国際化（i18n）', link: '/guides/i18n/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +				{ label: 'コンポーネント', link: '/ja/guides/components/' },
```suggestion
				{ label: 'コンポーネント', link: '/guides/components/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +				{ label: '国際化（i18n）', link: '/ja/guides/i18n/' },
```suggestion
				{ label: '国際化（i18n）', link: '/guides/i18n/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +						{ label: 'CSS', link: '/ja/guides/css-and-tailwind/' },
```suggestion
						{ label: 'CSS', link: '/guides/css-and-tailwind/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +						{ label: 'Tailwind', link: '/ja/guides/css-and-tailwind/' },
```suggestion
						{ label: 'Tailwind', link: '/guides/css-and-tailwind/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +						{ label: 'Shiki', link: '/ja/guides/css-and-tailwind/' },
```suggestion
						{ label: 'Shiki', link: '/guides/css-and-tailwind/' },
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +					link: '/ja/guides/components/',
```suggestion
					link: '/guides/components/',
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +					link: '/ja/guides/components/',
```suggestion
					link: '/guides/components/',
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +					link: '/ja/guides/components/',
```suggestion
					link: '/guides/components/',
```

2023-09-28 15:40 UTC, trueberryless commented on docs/src/content/docs/ja/guides/sidebar.mdx
> +					link: '/ja/guides/components/',
```suggestion
					link: '/guides/components/',
```

2023-10-05 23:00 UTC, delucis approved these changes
Thank you for this translation @morinokami and for the review @trueberryless!

I accepted the suggestions inside the code examples but not inside the `<SidebarPreview>` components. My reasoning here is that in your Starlight config you usually do not always include the language segment in links (e.g. `/ja/`). But Starlight will add the language segment for you if needed, so our preview components can still show the `/ja/` links.

2023-10-05 23:01 UTC, merged