i18n(es): Update `guides/customization.mdx` and `reference/configuration.md`
withastro/starlight pull request #800
Opened 2023-10-03 11:48 UTC by K1ri86

#### What kind of changes does this PR include?
- Changes or translations of Starlight docs site content

#### Description
- What does this PR change? Give us a brief description.
- Update #752

2023-10-03 15:06 UTC, K1ri86 commented
> Thank you for the PR @K1ri86!
> 
> There were also two more changes to these files adding Telegram and RSS icons:
> 
> * [a0de12d](https://github.com/withastro/starlight/commit/a0de12d596ab2b1c0d79d6d63d2d6cb9fe6d2644)
> * [a8358df](https://github.com/withastro/starlight/commit/a8358df7849b342de342a4a2e88e019c39d5bbe8)
> 
> Would you be able to update this PR to include those as well?

Done 🚀

2023-10-03 15:27 UTC, K1ri86 commented on docs/src/content/docs/es/guides/customization.mdx
> +Actualmente, se admiten enlaces a Bitbucket, Codeberg, CodePen, Discord, GitHub, GitLab, Gitter, Instagram, LinkedIn, Mastodon, Microsoft Teams, an RSS feed, Stack Overflow, Telegram, Threads, Twitch
> Just to double check, is "an RSS feed" actually properly translated or could have been forgotten?

I just made the change 👍🏻

2023-10-03 17:59 UTC, kevinzunigacuellar approved these changes
LGTM!

2023-10-03 19:45 UTC, dreyfus92 requested changes
Awesome job @K1ri86, I left you a minor suggestion 😁

2023-10-03 19:45 UTC, dreyfus92 commented on docs/src/content/docs/es/guides/customization.mdx
> +Actualmente, se admiten enlaces a Bitbucket, Codeberg, CodePen, Discord, GitHub, GitLab, Gitter, Instagram, LinkedIn, Mastodon, Microsoft Teams, RSS feed, Stack Overflow, Telegram, Threads, Twitch, T
```suggestion
Actualmente, se admiten enlaces a Bitbucket, Codeberg, CodePen, Discord, GitHub, GitLab, Gitter, Instagram, LinkedIn, Mastodon, Microsoft Teams, un flujo RSS, Stack Overflow, Telegram, Threads, Twitch, Twitter, X, y Youtube ¡Háznoslo saber en GitHub o Discord si necesitas soporte para otro servicio!
```

2023-10-04 00:29 UTC, Waxer59 approved these changes
LGTM ✔

2023-10-04 12:54 UTC, delucis approved these changes
Thanks again @K1ri86 and everyone who reviewed. Great team work 🙌

2023-10-04 12:56 UTC, merged