i18n(vi): add Vietnames translation for Starlight UI
withastro/starlight pull request #807
Opened 2023-10-04 15:08 UTC by torn4dom4n

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- Add Vietnamese translation for Starlight UI

I'm taking part in Hacktoberfest.

2023-10-05 13:59 UTC, HiDeoo reviewed
Thanks for your contribution :raised_hands:

From a purely technical point of view, adding a new language will require 2 additional changes:

- Adding the language to the list of supported languages in the documentation (https://github.com/withastro/starlight/blob/main/docs/src/content/docs/guides/i18n.mdx#L146)
- Adding a changeset describing the change (you can easily create one by running `pnpm exec changeset`)

If needed, [this PR](https://github.com/withastro/starlight/pull/537/files) adding the Swedish language can be used as a reference.

_I've added the Hacktoberfest label._

2023-10-05 19:59 UTC, HiDeoo requested changes
Thanks for the update.

Left a small suggestion for the changeset but except that, this looks good to me 👍

2023-10-05 19:59 UTC, HiDeoo commented on .changeset/good-ways-jump.md
> +"starlight-docs": patch
```suggestion
```

Docs do not need to be tracked in the changeset.

2023-10-05 22:20 UTC, delucis reviewed
This looks great @torn4dom4n! Thanks again for making this PR.

One more tiny thing from me, but that and @HiDeoo’s suggestion should be all that’s left to ship this 🚀

2023-10-05 22:20 UTC, delucis commented on docs/src/content/docs/guides/i18n.mdx
> +English, Czech, French, German, Italian, Japanese, Portuguese, Dutch, Danish, Spanish, Turkish, Arabic, Norwegian, Farsi, Hebrew, Simplified Chinese, Korean, Indonesian, Russian, Swedish and Vietname
Small gotcha here that we need an “Oxford comma” before the “and”:
```suggestion
English, Czech, French, German, Italian, Japanese, Portuguese, Dutch, Danish, Spanish, Turkish, Arabic, Norwegian, Farsi, Hebrew, Simplified Chinese, Korean, Indonesian, Russian, Swedish, and Vietnamese translated UI strings are provided out of the box, and we welcome [contributions to add more default languages](https://github.com/withastro/starlight/blob/main/CONTRIBUTING.md).
```

2023-10-05 23:06 UTC, delucis approved these changes
Thanks for fixing those!

Looks good to go! Will merge this tomorrow as part of our next release. Thanks again for contributing this @torn4dom4n 🙌

2023-10-06 05:15 UTC, HiDeoo approved these changes

2023-10-06 15:53 UTC, merged