i18n(tr): add `sidebar.mdx`
withastro/starlight pull request #920
Opened 2023-10-16 19:51 UTC by erkanaltinors

#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- This pull request adds translated in turkish `sidebar.mdx` file into `tr/guides`

2023-10-17 06:54 UTC, HiDeoo reviewed
Thanks for the translation.

I think this may be missing the changes from #881 which adds details about BCP-47 language tags and uses a BCP-47 language tag with a regional subtag for the "Internationalization" section example.

2023-10-17 09:05 UTC, erkanaltinors commented
Hi @HiDeoo thanks for your response. I will add this block into the page.

2023-10-23 14:03 UTC, delucis requested changes
Thanks for the translation @erkanaltinors! Just noticed a few links that need updating, but otherwise looks good to me 👍

2023-10-23 14:03 UTC, delucis commented on docs/src/content/docs/tr/guides/sidebar.mdx
> +Kenar çubuğu önbölüm ayarları bir bağlantıya [özel isim](/tr/reference/frontmatter/#label) ya da [etiket](/tr/reference/frontmatter/#badge) eklemenize, kenar çubuğundan bir bağlantı [gizlemenize](/re
Same here — some of these need updating to include `/tr/`:

```suggestion
Özel sayfalarınızda [`kenar çubuğu` önbölüm alanı](/tr/reference/frontmatter/#sidebar)'nı otomatik oluşturulan bağlantılarınızı özelleştirmek için kullanın.

Kenar çubuğu önbölüm ayarları bir bağlantıya [özel isim](/tr/reference/frontmatter/#label) ya da [etiket](/tr/reference/frontmatter/#badge) eklemenize, kenar çubuğundan bir bağlantı [gizlemenize](/tr/reference/frontmatter/#hidden) ya da [özel sıralama](/tr/reference/frontmatter/#order) tanımlamanıza olanak sağlar.
```

2023-10-23 14:03 UTC, delucis commented on docs/src/content/docs/tr/guides/sidebar.mdx
> +[Otomatik oluşturulmuş gruplar](#autogenerated-groups) `collapsed` değerinin üst grubuna dikkat eder:
This link needs to be to the Turkish slug:
```suggestion
[Otomatik oluşturulmuş gruplar](#otomatik-oluşturulmuş-gruplar) `collapsed` değerinin üst grubuna dikkat eder:
```

2023-10-23 18:08 UTC, erkanaltinors commented
Hi @delucis , I will fix them in this week. Thank you for your feedback 🤠

2023-10-23 20:44 UTC, delucis commented
Thanks @erkanaltinors! You should be able to click the <kbd>Commit suggestion</kbd> buttons in this PR to accept the suggested fixes.

2023-10-23 21:04 UTC, erkanaltinors commented
I've accepted all suggested fixes @delucis 🚀

2023-10-23 22:09 UTC, delucis approved these changes
Awesome! Thanks @erkanaltinors 💫

2023-10-23 22:09 UTC, merged